// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.OpenAI.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.ApplyPatchCreateFileOperationParam"/>, <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.ApplyPatchDeleteFileOperationParam"/>, <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.ApplyPatchUpdateFileOperationParam"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ApplyPatchOperationParam : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.ApplyPatchCreateFileOperationParam"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.ApplyPatchCreateFileOperationParam? ApplyPatchCreateFileOperationParam { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.ApplyPatchCreateFileOperationParam ApplyPatchCreateFileOperationParam { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.ApplyPatchDeleteFileOperationParam"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.ApplyPatchDeleteFileOperationParam? ApplyPatchDeleteFileOperationParam { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.ApplyPatchDeleteFileOperationParam ApplyPatchDeleteFileOperationParam { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.ApplyPatchUpdateFileOperationParam"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.ApplyPatchUpdateFileOperationParam? ApplyPatchUpdateFileOperationParam { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.ApplyPatchUpdateFileOperationParam ApplyPatchUpdateFileOperationParam { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.ApplyPatchOperationParam"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.OpenAI.OpenApiClient.Models.ApplyPatchOperationParam CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            var result = new global::Soenneker.OpenAI.OpenApiClient.Models.ApplyPatchOperationParam();
            if("ApplyPatchCreateFileOperationParam".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ApplyPatchCreateFileOperationParam = new global::Soenneker.OpenAI.OpenApiClient.Models.ApplyPatchCreateFileOperationParam();
            }
            else if("ApplyPatchDeleteFileOperationParam".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ApplyPatchDeleteFileOperationParam = new global::Soenneker.OpenAI.OpenApiClient.Models.ApplyPatchDeleteFileOperationParam();
            }
            else if("ApplyPatchUpdateFileOperationParam".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ApplyPatchUpdateFileOperationParam = new global::Soenneker.OpenAI.OpenApiClient.Models.ApplyPatchUpdateFileOperationParam();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(ApplyPatchCreateFileOperationParam != null)
            {
                return ApplyPatchCreateFileOperationParam.GetFieldDeserializers();
            }
            else if(ApplyPatchDeleteFileOperationParam != null)
            {
                return ApplyPatchDeleteFileOperationParam.GetFieldDeserializers();
            }
            else if(ApplyPatchUpdateFileOperationParam != null)
            {
                return ApplyPatchUpdateFileOperationParam.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(ApplyPatchCreateFileOperationParam != null)
            {
                writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.ApplyPatchCreateFileOperationParam>(null, ApplyPatchCreateFileOperationParam);
            }
            else if(ApplyPatchDeleteFileOperationParam != null)
            {
                writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.ApplyPatchDeleteFileOperationParam>(null, ApplyPatchDeleteFileOperationParam);
            }
            else if(ApplyPatchUpdateFileOperationParam != null)
            {
                writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.ApplyPatchUpdateFileOperationParam>(null, ApplyPatchUpdateFileOperationParam);
            }
        }
    }
}
#pragma warning restore CS0618
