// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.OpenAI.OpenApiClient.Models
{
    /// <summary>
    /// The payload used to update the role.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AuditLog_roleUpdated_changes_requested : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The updated role description, when provided.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>Additional metadata stored on the role.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.AuditLog_roleUpdated_changes_requested_metadata? Metadata { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.AuditLog_roleUpdated_changes_requested_metadata Metadata { get; set; }
#endif
        /// <summary>The permissions added to the role.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? PermissionsAdded { get; set; }
#nullable restore
#else
        public List<string> PermissionsAdded { get; set; }
#endif
        /// <summary>The permissions removed from the role.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? PermissionsRemoved { get; set; }
#nullable restore
#else
        public List<string> PermissionsRemoved { get; set; }
#endif
        /// <summary>The resource the role is scoped to.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ResourceId { get; set; }
#nullable restore
#else
        public string ResourceId { get; set; }
#endif
        /// <summary>The type of resource the role belongs to.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ResourceType { get; set; }
#nullable restore
#else
        public string ResourceType { get; set; }
#endif
        /// <summary>The updated role name, when provided.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RoleName { get; set; }
#nullable restore
#else
        public string RoleName { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.AuditLog_roleUpdated_changes_requested"/> and sets the default values.
        /// </summary>
        public AuditLog_roleUpdated_changes_requested()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.AuditLog_roleUpdated_changes_requested"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.OpenAI.OpenApiClient.Models.AuditLog_roleUpdated_changes_requested CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.OpenAI.OpenApiClient.Models.AuditLog_roleUpdated_changes_requested();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "description", n => { Description = n.GetStringValue(); } },
                { "metadata", n => { Metadata = n.GetObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.AuditLog_roleUpdated_changes_requested_metadata>(global::Soenneker.OpenAI.OpenApiClient.Models.AuditLog_roleUpdated_changes_requested_metadata.CreateFromDiscriminatorValue); } },
                { "permissions_added", n => { PermissionsAdded = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "permissions_removed", n => { PermissionsRemoved = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "resource_id", n => { ResourceId = n.GetStringValue(); } },
                { "resource_type", n => { ResourceType = n.GetStringValue(); } },
                { "role_name", n => { RoleName = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("description", Description);
            writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.AuditLog_roleUpdated_changes_requested_metadata>("metadata", Metadata);
            writer.WriteCollectionOfPrimitiveValues<string>("permissions_added", PermissionsAdded);
            writer.WriteCollectionOfPrimitiveValues<string>("permissions_removed", PermissionsRemoved);
            writer.WriteStringValue("resource_id", ResourceId);
            writer.WriteStringValue("resource_type", ResourceType);
            writer.WriteStringValue("role_name", RoleName);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
