// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.OpenAI.OpenApiClient.Models
{
    /// <summary>
    /// Execute a shell command on the server.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class BetaLocalShellExecAction : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The command to run.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Command { get; set; }
#nullable restore
#else
        public List<string> Command { get; set; }
#endif
        /// <summary>Environment variables to set for the command.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.BetaLocalShellExecActionEnvProperty? Env { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.BetaLocalShellExecActionEnvProperty Env { get; set; }
#endif
        /// <summary>The timeout_ms property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.BetaLocalShellExecActionTimeoutMs? TimeoutMs { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.BetaLocalShellExecActionTimeoutMs TimeoutMs { get; set; }
#endif
        /// <summary>The type of the local shell action. Always `exec`.</summary>
        public global::Soenneker.OpenAI.OpenApiClient.Models.BetaLocalShellExecActionType? Type { get; set; }
        /// <summary>The user property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.BetaLocalShellExecActionUser? User { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.BetaLocalShellExecActionUser User { get; set; }
#endif
        /// <summary>The working_directory property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.BetaLocalShellExecActionWorkingDirectory? WorkingDirectory { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.BetaLocalShellExecActionWorkingDirectory WorkingDirectory { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.BetaLocalShellExecAction"/> and sets the default values.
        /// </summary>
        public BetaLocalShellExecAction()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.BetaLocalShellExecAction"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.OpenAI.OpenApiClient.Models.BetaLocalShellExecAction CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.OpenAI.OpenApiClient.Models.BetaLocalShellExecAction();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "command", n => { Command = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "env", n => { Env = n.GetObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.BetaLocalShellExecActionEnvProperty>(global::Soenneker.OpenAI.OpenApiClient.Models.BetaLocalShellExecActionEnvProperty.CreateFromDiscriminatorValue); } },
                { "timeout_ms", n => { TimeoutMs = n.GetObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.BetaLocalShellExecActionTimeoutMs>(global::Soenneker.OpenAI.OpenApiClient.Models.BetaLocalShellExecActionTimeoutMs.CreateFromDiscriminatorValue); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.OpenAI.OpenApiClient.Models.BetaLocalShellExecActionType>(); } },
                { "user", n => { User = n.GetObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.BetaLocalShellExecActionUser>(global::Soenneker.OpenAI.OpenApiClient.Models.BetaLocalShellExecActionUser.CreateFromDiscriminatorValue); } },
                { "working_directory", n => { WorkingDirectory = n.GetObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.BetaLocalShellExecActionWorkingDirectory>(global::Soenneker.OpenAI.OpenApiClient.Models.BetaLocalShellExecActionWorkingDirectory.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<string>("command", Command);
            writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.BetaLocalShellExecActionEnvProperty>("env", Env);
            writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.BetaLocalShellExecActionTimeoutMs>("timeout_ms", TimeoutMs);
            writer.WriteEnumValue<global::Soenneker.OpenAI.OpenApiClient.Models.BetaLocalShellExecActionType>("type", Type);
            writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.BetaLocalShellExecActionUser>("user", User);
            writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.BetaLocalShellExecActionWorkingDirectory>("working_directory", WorkingDirectory);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
