// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.OpenAI.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class BetaCreateResponseBody : global::Soenneker.OpenAI.OpenApiClient.Models.BetaCreateModelResponseProperties, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Whether to run the model response in the background.[Learn more](/docs/guides/background).</summary>
        public bool? Background { get; set; }
        /// <summary>The context_management property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.OpenAI.OpenApiClient.Models.BetaContextManagementParam>? ContextManagement { get; set; }
#nullable restore
#else
        public List<global::Soenneker.OpenAI.OpenApiClient.Models.BetaContextManagementParam> ContextManagement { get; set; }
#endif
        /// <summary>The conversation property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.BetaConversationParam? Conversation { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.BetaConversationParam Conversation { get; set; }
#endif
        /// <summary>The include property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.OpenAI.OpenApiClient.Models.BetaIncludeEnum?>? Include { get; set; }
#nullable restore
#else
        public List<global::Soenneker.OpenAI.OpenApiClient.Models.BetaIncludeEnum?> Include { get; set; }
#endif
        /// <summary>Text, image, or file inputs to the model, used to generate a response.Learn more:- [Text inputs and outputs](/docs/guides/text)- [Image inputs](/docs/guides/images)- [File inputs](/docs/guides/pdf-files)- [Conversation state](/docs/guides/conversation-state)- [Function calling](/docs/guides/function-calling)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.BetaInputParam? Input { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.BetaInputParam Input { get; set; }
#endif
        /// <summary>A system (or developer) message inserted into the model&apos;s context.When using along with `previous_response_id`, the instructions from a previousresponse will not be carried over to the next response. This makes it simpleto swap out system (or developer) messages in new responses.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Instructions { get; set; }
#nullable restore
#else
        public string Instructions { get; set; }
#endif
        /// <summary>An upper bound for the number of tokens that can be generated for a response, including visible output tokens and [reasoning tokens](/docs/guides/reasoning).</summary>
        public int? MaxOutputTokens { get; set; }
        /// <summary>The maximum number of total calls to built-in tools that can be processed in a response. This maximum number applies across all built-in tool calls, not per individual tool. Any further attempts to call a tool by the model will be ignored.</summary>
        public int? MaxToolCalls { get; set; }
        /// <summary>Model ID used to generate the response, like `gpt-4o` or `o3`. OpenAIoffers a wide range of models with different capabilities, performancecharacteristics, and price points. Refer to the [model guide](/docs/models)to browse and compare available models.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.BetaModelIdsResponses? Model { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.BetaModelIdsResponses Model { get; set; }
#endif
        /// <summary>The moderation property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.BetaModerationParam? Moderation { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.BetaModerationParam Moderation { get; set; }
#endif
        /// <summary>The multi_agent property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.BetaMultiAgentParam? MultiAgent { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.BetaMultiAgentParam MultiAgent { get; set; }
#endif
        /// <summary>Whether to allow the model to run tool calls in parallel.</summary>
        public bool? ParallelToolCalls { get; set; }
        /// <summary>The unique ID of the previous response to the model. Use this tocreate multi-turn conversations. Learn more about[conversation state](/docs/guides/conversation-state). Cannot be used in conjunction with `conversation`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PreviousResponseId { get; set; }
#nullable restore
#else
        public string PreviousResponseId { get; set; }
#endif
        /// <summary>Reference to a prompt template and its variables.[Learn more](/docs/guides/text?api-mode=responses#reusable-prompts).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.BetaPrompt? Prompt { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.BetaPrompt Prompt { get; set; }
#endif
        /// <summary>The reasoning property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.BetaReasoning? Reasoning { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.BetaReasoning Reasoning { get; set; }
#endif
        /// <summary>Whether to store the generated model response for later retrieval viaAPI.</summary>
        public bool? Store { get; set; }
        /// <summary>If set to true, the model response data will be streamed to the clientas it is generated using [server-sent events](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events#Event_stream_format).See the [Streaming section below](/docs/api-reference/responses-streaming)for more information.</summary>
        public bool? Stream { get; set; }
        /// <summary>&quot;Options for streaming responses. Only set this when you set `stream: true`.&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.BetaResponseStreamOptions? StreamOptions { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.BetaResponseStreamOptions StreamOptions { get; set; }
#endif
        /// <summary>Configuration options for a text response from the model. Can be plaintext or structured JSON data. Learn more:- [Text inputs and outputs](/docs/guides/text)- [Structured Outputs](/docs/guides/structured-outputs)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.BetaResponseTextParam? Text { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.BetaResponseTextParam Text { get; set; }
#endif
        /// <summary>How the model should select which tool (or tools) to use when generatinga response. See the `tools` parameter to see how to specify which toolsthe model can call.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.BetaToolChoiceParam? ToolChoice { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.BetaToolChoiceParam ToolChoice { get; set; }
#endif
        /// <summary>&quot;An array of tools the model may call while generating a response. Youcan specify which tool to use by setting the `tool_choice` parameter.We support the following categories of tools:- **Built-in tools**: Tools that are provided by OpenAI that extend the  model&apos;s capabilities, like [web search](/docs/guides/tools-web-search)  or [file search](/docs/guides/tools-file-search). Learn more about  [built-in tools](/docs/guides/tools).- **MCP Tools**: Integrations with third-party systems via custom MCP servers  or predefined connectors such as Google Drive and SharePoint. Learn more about  [MCP Tools](/docs/guides/tools-connectors-mcp).- **Function calls (custom tools)**: Functions that are defined by you,  enabling the model to call your own code with strongly typed arguments  and outputs. Learn more about  [function calling](/docs/guides/function-calling). You can also use  custom tools to call your own code.&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.OpenAI.OpenApiClient.Models.BetaTool>? Tools { get; set; }
#nullable restore
#else
        public List<global::Soenneker.OpenAI.OpenApiClient.Models.BetaTool> Tools { get; set; }
#endif
        /// <summary>&quot;The truncation strategy to use for the model response.- `auto`: If the input to this Response exceeds  the model&apos;s context window size, the model will truncate the  response to fit the context window by dropping items from the beginning of the conversation.- `disabled` (default): If the input size will exceed the context window  size for a model, the request will fail with a 400 error.&quot;</summary>
        [Obsolete("")]
        public global::Soenneker.OpenAI.OpenApiClient.Models.BetaCreateResponseBodyTruncation? Truncation { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.BetaCreateResponseBody"/> and sets the default values.
        /// </summary>
        public BetaCreateResponseBody() : base()
        {
            Background = false;
            ParallelToolCalls = true;
            Store = true;
            Stream = false;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.BetaCreateResponseBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::Soenneker.OpenAI.OpenApiClient.Models.BetaCreateResponseBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.OpenAI.OpenApiClient.Models.BetaCreateResponseBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "background", n => { Background = n.GetBoolValue(); } },
                { "context_management", n => { ContextManagement = n.GetCollectionOfObjectValues<global::Soenneker.OpenAI.OpenApiClient.Models.BetaContextManagementParam>(global::Soenneker.OpenAI.OpenApiClient.Models.BetaContextManagementParam.CreateFromDiscriminatorValue)?.AsList(); } },
                { "conversation", n => { Conversation = n.GetObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.BetaConversationParam>(global::Soenneker.OpenAI.OpenApiClient.Models.BetaConversationParam.CreateFromDiscriminatorValue); } },
                { "include", n => { Include = n.GetCollectionOfEnumValues<global::Soenneker.OpenAI.OpenApiClient.Models.BetaIncludeEnum>()?.AsList(); } },
                { "input", n => { Input = n.GetObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.BetaInputParam>(global::Soenneker.OpenAI.OpenApiClient.Models.BetaInputParam.CreateFromDiscriminatorValue); } },
                { "instructions", n => { Instructions = n.GetStringValue(); } },
                { "max_output_tokens", n => { MaxOutputTokens = n.GetIntValue(); } },
                { "max_tool_calls", n => { MaxToolCalls = n.GetIntValue(); } },
                { "model", n => { Model = n.GetObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.BetaModelIdsResponses>(global::Soenneker.OpenAI.OpenApiClient.Models.BetaModelIdsResponses.CreateFromDiscriminatorValue); } },
                { "moderation", n => { Moderation = n.GetObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.BetaModerationParam>(global::Soenneker.OpenAI.OpenApiClient.Models.BetaModerationParam.CreateFromDiscriminatorValue); } },
                { "multi_agent", n => { MultiAgent = n.GetObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.BetaMultiAgentParam>(global::Soenneker.OpenAI.OpenApiClient.Models.BetaMultiAgentParam.CreateFromDiscriminatorValue); } },
                { "parallel_tool_calls", n => { ParallelToolCalls = n.GetBoolValue(); } },
                { "previous_response_id", n => { PreviousResponseId = n.GetStringValue(); } },
                { "prompt", n => { Prompt = n.GetObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.BetaPrompt>(global::Soenneker.OpenAI.OpenApiClient.Models.BetaPrompt.CreateFromDiscriminatorValue); } },
                { "reasoning", n => { Reasoning = n.GetObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.BetaReasoning>(global::Soenneker.OpenAI.OpenApiClient.Models.BetaReasoning.CreateFromDiscriminatorValue); } },
                { "store", n => { Store = n.GetBoolValue(); } },
                { "stream", n => { Stream = n.GetBoolValue(); } },
                { "stream_options", n => { StreamOptions = n.GetObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.BetaResponseStreamOptions>(global::Soenneker.OpenAI.OpenApiClient.Models.BetaResponseStreamOptions.CreateFromDiscriminatorValue); } },
                { "text", n => { Text = n.GetObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.BetaResponseTextParam>(global::Soenneker.OpenAI.OpenApiClient.Models.BetaResponseTextParam.CreateFromDiscriminatorValue); } },
                { "tool_choice", n => { ToolChoice = n.GetObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.BetaToolChoiceParam>(global::Soenneker.OpenAI.OpenApiClient.Models.BetaToolChoiceParam.CreateFromDiscriminatorValue); } },
                { "tools", n => { Tools = n.GetCollectionOfObjectValues<global::Soenneker.OpenAI.OpenApiClient.Models.BetaTool>(global::Soenneker.OpenAI.OpenApiClient.Models.BetaTool.CreateFromDiscriminatorValue)?.AsList(); } },
                { "truncation", n => { Truncation = n.GetEnumValue<global::Soenneker.OpenAI.OpenApiClient.Models.BetaCreateResponseBodyTruncation>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteBoolValue("background", Background);
            writer.WriteCollectionOfObjectValues<global::Soenneker.OpenAI.OpenApiClient.Models.BetaContextManagementParam>("context_management", ContextManagement);
            writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.BetaConversationParam>("conversation", Conversation);
            writer.WriteCollectionOfEnumValues<global::Soenneker.OpenAI.OpenApiClient.Models.BetaIncludeEnum>("include", Include);
            writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.BetaInputParam>("input", Input);
            writer.WriteStringValue("instructions", Instructions);
            writer.WriteIntValue("max_output_tokens", MaxOutputTokens);
            writer.WriteIntValue("max_tool_calls", MaxToolCalls);
            writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.BetaModelIdsResponses>("model", Model);
            writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.BetaModerationParam>("moderation", Moderation);
            writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.BetaMultiAgentParam>("multi_agent", MultiAgent);
            writer.WriteBoolValue("parallel_tool_calls", ParallelToolCalls);
            writer.WriteStringValue("previous_response_id", PreviousResponseId);
            writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.BetaPrompt>("prompt", Prompt);
            writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.BetaReasoning>("reasoning", Reasoning);
            writer.WriteBoolValue("store", Store);
            writer.WriteBoolValue("stream", Stream);
            writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.BetaResponseStreamOptions>("stream_options", StreamOptions);
            writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.BetaResponseTextParam>("text", Text);
            writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.BetaToolChoiceParam>("tool_choice", ToolChoice);
            writer.WriteCollectionOfObjectValues<global::Soenneker.OpenAI.OpenApiClient.Models.BetaTool>("tools", Tools);
            writer.WriteEnumValue<global::Soenneker.OpenAI.OpenApiClient.Models.BetaCreateResponseBodyTruncation>("truncation", Truncation);
        }
    }
}
#pragma warning restore CS0618
