// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.OpenAI.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.BetaComputerScreenshotContent"/>, <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.BetaEncryptedContent"/>, <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.BetaInputFileContent"/>, <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.BetaInputImageContent"/>, <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.BetaInputTextContent"/>, <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.BetaOutputTextContent"/>, <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.BetaReasoningTextContent"/>, <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.BetaRefusalContent"/>, <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.BetaSummaryTextContent"/>, <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.BetaTextContent"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class BetaAgentMessageContentItem : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.BetaComputerScreenshotContent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.BetaComputerScreenshotContent? BetaComputerScreenshotContent { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.BetaComputerScreenshotContent BetaComputerScreenshotContent { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.BetaEncryptedContent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.BetaEncryptedContent? BetaEncryptedContent { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.BetaEncryptedContent BetaEncryptedContent { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.BetaInputFileContent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.BetaInputFileContent? BetaInputFileContent { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.BetaInputFileContent BetaInputFileContent { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.BetaInputImageContent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.BetaInputImageContent? BetaInputImageContent { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.BetaInputImageContent BetaInputImageContent { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.BetaInputTextContent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.BetaInputTextContent? BetaInputTextContent { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.BetaInputTextContent BetaInputTextContent { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.BetaOutputTextContent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.BetaOutputTextContent? BetaOutputTextContent { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.BetaOutputTextContent BetaOutputTextContent { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.BetaReasoningTextContent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.BetaReasoningTextContent? BetaReasoningTextContent { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.BetaReasoningTextContent BetaReasoningTextContent { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.BetaRefusalContent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.BetaRefusalContent? BetaRefusalContent { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.BetaRefusalContent BetaRefusalContent { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.BetaSummaryTextContent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.BetaSummaryTextContent? BetaSummaryTextContent { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.BetaSummaryTextContent BetaSummaryTextContent { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.BetaTextContent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.BetaTextContent? BetaTextContent { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.BetaTextContent BetaTextContent { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.BetaAgentMessageContentItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.OpenAI.OpenApiClient.Models.BetaAgentMessageContentItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            var result = new global::Soenneker.OpenAI.OpenApiClient.Models.BetaAgentMessageContentItem();
            if("BetaComputerScreenshotContent".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.BetaComputerScreenshotContent = new global::Soenneker.OpenAI.OpenApiClient.Models.BetaComputerScreenshotContent();
            }
            else if("BetaEncryptedContent".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.BetaEncryptedContent = new global::Soenneker.OpenAI.OpenApiClient.Models.BetaEncryptedContent();
            }
            else if("BetaInputFileContent".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.BetaInputFileContent = new global::Soenneker.OpenAI.OpenApiClient.Models.BetaInputFileContent();
            }
            else if("BetaInputImageContent".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.BetaInputImageContent = new global::Soenneker.OpenAI.OpenApiClient.Models.BetaInputImageContent();
            }
            else if("BetaInputTextContent".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.BetaInputTextContent = new global::Soenneker.OpenAI.OpenApiClient.Models.BetaInputTextContent();
            }
            else if("BetaOutputTextContent".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.BetaOutputTextContent = new global::Soenneker.OpenAI.OpenApiClient.Models.BetaOutputTextContent();
            }
            else if("BetaReasoningTextContent".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.BetaReasoningTextContent = new global::Soenneker.OpenAI.OpenApiClient.Models.BetaReasoningTextContent();
            }
            else if("BetaRefusalContent".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.BetaRefusalContent = new global::Soenneker.OpenAI.OpenApiClient.Models.BetaRefusalContent();
            }
            else if("BetaSummaryTextContent".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.BetaSummaryTextContent = new global::Soenneker.OpenAI.OpenApiClient.Models.BetaSummaryTextContent();
            }
            else if("BetaTextContent".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.BetaTextContent = new global::Soenneker.OpenAI.OpenApiClient.Models.BetaTextContent();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(BetaComputerScreenshotContent != null)
            {
                return BetaComputerScreenshotContent.GetFieldDeserializers();
            }
            else if(BetaEncryptedContent != null)
            {
                return BetaEncryptedContent.GetFieldDeserializers();
            }
            else if(BetaInputFileContent != null)
            {
                return BetaInputFileContent.GetFieldDeserializers();
            }
            else if(BetaInputImageContent != null)
            {
                return BetaInputImageContent.GetFieldDeserializers();
            }
            else if(BetaInputTextContent != null)
            {
                return BetaInputTextContent.GetFieldDeserializers();
            }
            else if(BetaOutputTextContent != null)
            {
                return BetaOutputTextContent.GetFieldDeserializers();
            }
            else if(BetaReasoningTextContent != null)
            {
                return BetaReasoningTextContent.GetFieldDeserializers();
            }
            else if(BetaRefusalContent != null)
            {
                return BetaRefusalContent.GetFieldDeserializers();
            }
            else if(BetaSummaryTextContent != null)
            {
                return BetaSummaryTextContent.GetFieldDeserializers();
            }
            else if(BetaTextContent != null)
            {
                return BetaTextContent.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(BetaComputerScreenshotContent != null)
            {
                writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.BetaComputerScreenshotContent>(null, BetaComputerScreenshotContent);
            }
            else if(BetaEncryptedContent != null)
            {
                writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.BetaEncryptedContent>(null, BetaEncryptedContent);
            }
            else if(BetaInputFileContent != null)
            {
                writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.BetaInputFileContent>(null, BetaInputFileContent);
            }
            else if(BetaInputImageContent != null)
            {
                writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.BetaInputImageContent>(null, BetaInputImageContent);
            }
            else if(BetaInputTextContent != null)
            {
                writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.BetaInputTextContent>(null, BetaInputTextContent);
            }
            else if(BetaOutputTextContent != null)
            {
                writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.BetaOutputTextContent>(null, BetaOutputTextContent);
            }
            else if(BetaReasoningTextContent != null)
            {
                writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.BetaReasoningTextContent>(null, BetaReasoningTextContent);
            }
            else if(BetaRefusalContent != null)
            {
                writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.BetaRefusalContent>(null, BetaRefusalContent);
            }
            else if(BetaSummaryTextContent != null)
            {
                writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.BetaSummaryTextContent>(null, BetaSummaryTextContent);
            }
            else if(BetaTextContent != null)
            {
                writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.BetaTextContent>(null, BetaTextContent);
            }
        }
    }
}
#pragma warning restore CS0618
