// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.OpenAI.OpenApiClient.Models
{
    /// <summary>The provenance signal type. Always `c2pa`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum C2PaType
    {
        [EnumMember(Value = "c2pa")]
        #pragma warning disable CS1591
        C2Pa,
        #pragma warning restore CS1591
    }
}
