// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.OpenAI.OpenApiClient.Models
{
    /// <summary>For function calling, the type is always `function`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ChatCompletionNamedToolChoice_type
    {
        [EnumMember(Value = "function")]
        #pragma warning disable CS1591
        Function,
        #pragma warning restore CS1591
    }
}
