// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.OpenAI.OpenApiClient.Models
{
    /// <summary>The type of tool being defined: `code_interpreter`</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CodeInterpreterType
    {
        [EnumMember(Value = "code_interpreter")]
        #pragma warning disable CS1591
        CodeInterpreter,
        #pragma warning restore CS1591
    }
}
