// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.OpenAI.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CreateResponseBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The background property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.CreateResponseBody_background? Background { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.CreateResponseBody_background Background { get; set; }
#endif
        /// <summary>The context_management property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.CreateResponseBody_context_management? ContextManagement { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.CreateResponseBody_context_management ContextManagement { get; set; }
#endif
        /// <summary>The conversation property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.CreateResponseBody_conversation? Conversation { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.CreateResponseBody_conversation Conversation { get; set; }
#endif
        /// <summary>The include property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.CreateResponseBody_include? Include { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.CreateResponseBody_include Include { get; set; }
#endif
        /// <summary>Text, image, or file inputs to the model, used to generate a response.Learn more:- [Text inputs and outputs](/docs/guides/text)- [Image inputs](/docs/guides/images)- [File inputs](/docs/guides/pdf-files)- [Conversation state](/docs/guides/conversation-state)- [Function calling](/docs/guides/function-calling)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.InputParam? Input { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.InputParam Input { get; set; }
#endif
        /// <summary>The instructions property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.CreateResponseBody_instructions? Instructions { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.CreateResponseBody_instructions Instructions { get; set; }
#endif
        /// <summary>The max_output_tokens property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.CreateResponseBody_max_output_tokens? MaxOutputTokens { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.CreateResponseBody_max_output_tokens MaxOutputTokens { get; set; }
#endif
        /// <summary>The max_tool_calls property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.CreateResponseBody_max_tool_calls? MaxToolCalls { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.CreateResponseBody_max_tool_calls MaxToolCalls { get; set; }
#endif
        /// <summary>The metadata property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.Metadata? Metadata { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.Metadata Metadata { get; set; }
#endif
        /// <summary>The model property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.ModelIdsResponses? Model { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.ModelIdsResponses Model { get; set; }
#endif
        /// <summary>The parallel_tool_calls property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.CreateResponseBody_parallel_tool_calls? ParallelToolCalls { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.CreateResponseBody_parallel_tool_calls ParallelToolCalls { get; set; }
#endif
        /// <summary>The previous_response_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.CreateResponseBody_previous_response_id? PreviousResponseId { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.CreateResponseBody_previous_response_id PreviousResponseId { get; set; }
#endif
        /// <summary>The prompt property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.Prompt? Prompt { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.Prompt Prompt { get; set; }
#endif
        /// <summary>Used by OpenAI to cache responses for similar requests to optimize your cache hit rates. Replaces the `user` field. [Learn more](/docs/guides/prompt-caching).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PromptCacheKey { get; set; }
#nullable restore
#else
        public string PromptCacheKey { get; set; }
#endif
        /// <summary>The prompt_cache_retention property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.CreateResponseBody_prompt_cache_retention? PromptCacheRetention { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.CreateResponseBody_prompt_cache_retention PromptCacheRetention { get; set; }
#endif
        /// <summary>The reasoning property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.CreateResponseBody_reasoning? Reasoning { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.CreateResponseBody_reasoning Reasoning { get; set; }
#endif
        /// <summary>A stable identifier used to help detect users of your application that may be violating OpenAI&apos;s usage policies.The IDs should be a string that uniquely identifies each user, with a maximum length of 64 characters. We recommend hashing their username or email address, in order to avoid sending us any identifying information. [Learn more](/docs/guides/safety-best-practices#safety-identifiers).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SafetyIdentifier { get; set; }
#nullable restore
#else
        public string SafetyIdentifier { get; set; }
#endif
        /// <summary>The service_tier property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.ServiceTier? ServiceTier { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.ServiceTier ServiceTier { get; set; }
#endif
        /// <summary>The store property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.CreateResponseBody_store? Store { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.CreateResponseBody_store Store { get; set; }
#endif
        /// <summary>The stream property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.CreateResponseBody_stream? Stream { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.CreateResponseBody_stream Stream { get; set; }
#endif
        /// <summary>The stream_options property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.ResponseStreamOptions? StreamOptions { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.ResponseStreamOptions StreamOptions { get; set; }
#endif
        /// <summary>The temperature property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.CreateResponseBody_temperature? Temperature { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.CreateResponseBody_temperature Temperature { get; set; }
#endif
        /// <summary>Configuration options for a text response from the model. Can be plaintext or structured JSON data. Learn more:- [Text inputs and outputs](/docs/guides/text)- [Structured Outputs](/docs/guides/structured-outputs)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.ResponseTextParam? Text { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.ResponseTextParam Text { get; set; }
#endif
        /// <summary>How the model should select which tool (or tools) to use when generatinga response. See the `tools` parameter to see how to specify which toolsthe model can call.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.ToolChoiceParam? ToolChoice { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.ToolChoiceParam ToolChoice { get; set; }
#endif
        /// <summary>&quot;An array of tools the model may call while generating a response. Youcan specify which tool to use by setting the `tool_choice` parameter.We support the following categories of tools:- **Built-in tools**: Tools that are provided by OpenAI that extend the  model&apos;s capabilities, like [web search](/docs/guides/tools-web-search)  or [file search](/docs/guides/tools-file-search). Learn more about  [built-in tools](/docs/guides/tools).- **MCP Tools**: Integrations with third-party systems via custom MCP servers  or predefined connectors such as Google Drive and SharePoint. Learn more about  [MCP Tools](/docs/guides/tools-connectors-mcp).- **Function calls (custom tools)**: Functions that are defined by you,  enabling the model to call your own code with strongly typed arguments  and outputs. Learn more about  [function calling](/docs/guides/function-calling). You can also use  custom tools to call your own code.&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.OpenAI.OpenApiClient.Models.Tool>? Tools { get; set; }
#nullable restore
#else
        public List<global::Soenneker.OpenAI.OpenApiClient.Models.Tool> Tools { get; set; }
#endif
        /// <summary>The top_logprobs property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.CreateResponseBody_top_logprobs? TopLogprobs { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.CreateResponseBody_top_logprobs TopLogprobs { get; set; }
#endif
        /// <summary>The top_p property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.CreateResponseBody_top_p? TopP { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.CreateResponseBody_top_p TopP { get; set; }
#endif
        /// <summary>The truncation property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.CreateResponseBody_truncation? Truncation { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.CreateResponseBody_truncation Truncation { get; set; }
#endif
        /// <summary>This field is being replaced by `safety_identifier` and `prompt_cache_key`. Use `prompt_cache_key` instead to maintain caching optimizations.A stable identifier for your end-users.Used to boost cache hit rates by better bucketing similar requests and  to help OpenAI detect and prevent abuse. [Learn more](/docs/guides/safety-best-practices#safety-identifiers).</summary>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? User { get; set; }
#nullable restore
#else
        public string User { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.CreateResponseBody"/> and sets the default values.
        /// </summary>
        public CreateResponseBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.CreateResponseBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.OpenAI.OpenApiClient.Models.CreateResponseBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.OpenAI.OpenApiClient.Models.CreateResponseBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "background", n => { Background = n.GetObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.CreateResponseBody_background>(global::Soenneker.OpenAI.OpenApiClient.Models.CreateResponseBody_background.CreateFromDiscriminatorValue); } },
                { "context_management", n => { ContextManagement = n.GetObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.CreateResponseBody_context_management>(global::Soenneker.OpenAI.OpenApiClient.Models.CreateResponseBody_context_management.CreateFromDiscriminatorValue); } },
                { "conversation", n => { Conversation = n.GetObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.CreateResponseBody_conversation>(global::Soenneker.OpenAI.OpenApiClient.Models.CreateResponseBody_conversation.CreateFromDiscriminatorValue); } },
                { "include", n => { Include = n.GetObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.CreateResponseBody_include>(global::Soenneker.OpenAI.OpenApiClient.Models.CreateResponseBody_include.CreateFromDiscriminatorValue); } },
                { "input", n => { Input = n.GetObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.InputParam>(global::Soenneker.OpenAI.OpenApiClient.Models.InputParam.CreateFromDiscriminatorValue); } },
                { "instructions", n => { Instructions = n.GetObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.CreateResponseBody_instructions>(global::Soenneker.OpenAI.OpenApiClient.Models.CreateResponseBody_instructions.CreateFromDiscriminatorValue); } },
                { "max_output_tokens", n => { MaxOutputTokens = n.GetObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.CreateResponseBody_max_output_tokens>(global::Soenneker.OpenAI.OpenApiClient.Models.CreateResponseBody_max_output_tokens.CreateFromDiscriminatorValue); } },
                { "max_tool_calls", n => { MaxToolCalls = n.GetObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.CreateResponseBody_max_tool_calls>(global::Soenneker.OpenAI.OpenApiClient.Models.CreateResponseBody_max_tool_calls.CreateFromDiscriminatorValue); } },
                { "metadata", n => { Metadata = n.GetObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.Metadata>(global::Soenneker.OpenAI.OpenApiClient.Models.Metadata.CreateFromDiscriminatorValue); } },
                { "model", n => { Model = n.GetObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.ModelIdsResponses>(global::Soenneker.OpenAI.OpenApiClient.Models.ModelIdsResponses.CreateFromDiscriminatorValue); } },
                { "parallel_tool_calls", n => { ParallelToolCalls = n.GetObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.CreateResponseBody_parallel_tool_calls>(global::Soenneker.OpenAI.OpenApiClient.Models.CreateResponseBody_parallel_tool_calls.CreateFromDiscriminatorValue); } },
                { "previous_response_id", n => { PreviousResponseId = n.GetObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.CreateResponseBody_previous_response_id>(global::Soenneker.OpenAI.OpenApiClient.Models.CreateResponseBody_previous_response_id.CreateFromDiscriminatorValue); } },
                { "prompt", n => { Prompt = n.GetObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.Prompt>(global::Soenneker.OpenAI.OpenApiClient.Models.Prompt.CreateFromDiscriminatorValue); } },
                { "prompt_cache_key", n => { PromptCacheKey = n.GetStringValue(); } },
                { "prompt_cache_retention", n => { PromptCacheRetention = n.GetObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.CreateResponseBody_prompt_cache_retention>(global::Soenneker.OpenAI.OpenApiClient.Models.CreateResponseBody_prompt_cache_retention.CreateFromDiscriminatorValue); } },
                { "reasoning", n => { Reasoning = n.GetObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.CreateResponseBody_reasoning>(global::Soenneker.OpenAI.OpenApiClient.Models.CreateResponseBody_reasoning.CreateFromDiscriminatorValue); } },
                { "safety_identifier", n => { SafetyIdentifier = n.GetStringValue(); } },
                { "service_tier", n => { ServiceTier = n.GetObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.ServiceTier>(global::Soenneker.OpenAI.OpenApiClient.Models.ServiceTier.CreateFromDiscriminatorValue); } },
                { "store", n => { Store = n.GetObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.CreateResponseBody_store>(global::Soenneker.OpenAI.OpenApiClient.Models.CreateResponseBody_store.CreateFromDiscriminatorValue); } },
                { "stream", n => { Stream = n.GetObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.CreateResponseBody_stream>(global::Soenneker.OpenAI.OpenApiClient.Models.CreateResponseBody_stream.CreateFromDiscriminatorValue); } },
                { "stream_options", n => { StreamOptions = n.GetObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.ResponseStreamOptions>(global::Soenneker.OpenAI.OpenApiClient.Models.ResponseStreamOptions.CreateFromDiscriminatorValue); } },
                { "temperature", n => { Temperature = n.GetObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.CreateResponseBody_temperature>(global::Soenneker.OpenAI.OpenApiClient.Models.CreateResponseBody_temperature.CreateFromDiscriminatorValue); } },
                { "text", n => { Text = n.GetObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.ResponseTextParam>(global::Soenneker.OpenAI.OpenApiClient.Models.ResponseTextParam.CreateFromDiscriminatorValue); } },
                { "tool_choice", n => { ToolChoice = n.GetObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.ToolChoiceParam>(global::Soenneker.OpenAI.OpenApiClient.Models.ToolChoiceParam.CreateFromDiscriminatorValue); } },
                { "tools", n => { Tools = n.GetCollectionOfObjectValues<global::Soenneker.OpenAI.OpenApiClient.Models.Tool>(global::Soenneker.OpenAI.OpenApiClient.Models.Tool.CreateFromDiscriminatorValue)?.AsList(); } },
                { "top_logprobs", n => { TopLogprobs = n.GetObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.CreateResponseBody_top_logprobs>(global::Soenneker.OpenAI.OpenApiClient.Models.CreateResponseBody_top_logprobs.CreateFromDiscriminatorValue); } },
                { "top_p", n => { TopP = n.GetObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.CreateResponseBody_top_p>(global::Soenneker.OpenAI.OpenApiClient.Models.CreateResponseBody_top_p.CreateFromDiscriminatorValue); } },
                { "truncation", n => { Truncation = n.GetObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.CreateResponseBody_truncation>(global::Soenneker.OpenAI.OpenApiClient.Models.CreateResponseBody_truncation.CreateFromDiscriminatorValue); } },
                { "user", n => { User = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.CreateResponseBody_background>("background", Background);
            writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.CreateResponseBody_context_management>("context_management", ContextManagement);
            writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.CreateResponseBody_conversation>("conversation", Conversation);
            writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.CreateResponseBody_include>("include", Include);
            writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.InputParam>("input", Input);
            writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.CreateResponseBody_instructions>("instructions", Instructions);
            writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.CreateResponseBody_max_output_tokens>("max_output_tokens", MaxOutputTokens);
            writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.CreateResponseBody_max_tool_calls>("max_tool_calls", MaxToolCalls);
            writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.Metadata>("metadata", Metadata);
            writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.ModelIdsResponses>("model", Model);
            writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.CreateResponseBody_parallel_tool_calls>("parallel_tool_calls", ParallelToolCalls);
            writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.CreateResponseBody_previous_response_id>("previous_response_id", PreviousResponseId);
            writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.Prompt>("prompt", Prompt);
            writer.WriteStringValue("prompt_cache_key", PromptCacheKey);
            writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.CreateResponseBody_prompt_cache_retention>("prompt_cache_retention", PromptCacheRetention);
            writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.CreateResponseBody_reasoning>("reasoning", Reasoning);
            writer.WriteStringValue("safety_identifier", SafetyIdentifier);
            writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.ServiceTier>("service_tier", ServiceTier);
            writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.CreateResponseBody_store>("store", Store);
            writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.CreateResponseBody_stream>("stream", Stream);
            writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.ResponseStreamOptions>("stream_options", StreamOptions);
            writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.CreateResponseBody_temperature>("temperature", Temperature);
            writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.ResponseTextParam>("text", Text);
            writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.ToolChoiceParam>("tool_choice", ToolChoice);
            writer.WriteCollectionOfObjectValues<global::Soenneker.OpenAI.OpenApiClient.Models.Tool>("tools", Tools);
            writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.CreateResponseBody_top_logprobs>("top_logprobs", TopLogprobs);
            writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.CreateResponseBody_top_p>("top_p", TopP);
            writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.CreateResponseBody_truncation>("truncation", Truncation);
            writer.WriteStringValue("user", User);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
