// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.OpenAI.OpenApiClient.Models
{
    /// <summary>Allows to set transparency for the background of the generated image(s).This parameter is only supported for the GPT image models. Must be one of`transparent`, `opaque` or `auto` (default value). When `auto` is used, themodel will automatically determine the best background for the image.If `transparent`, the output format needs to support transparency, so itshould be set to either `png` (default value) or `webp`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CreateImageEditRequest_background
    {
        [EnumMember(Value = "transparent")]
        #pragma warning disable CS1591
        Transparent,
        #pragma warning restore CS1591
        [EnumMember(Value = "opaque")]
        #pragma warning disable CS1591
        Opaque,
        #pragma warning restore CS1591
        [EnumMember(Value = "auto")]
        #pragma warning disable CS1591
        Auto,
        #pragma warning restore CS1591
    }
}
