// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.OpenAI.OpenApiClient.Models
{
    /// <summary>The type of data source. Always `stored_completions`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CreateEvalStoredCompletionsDataSourceConfigType
    {
        [EnumMember(Value = "stored_completions")]
        #pragma warning disable CS1591
        StoredCompletions,
        #pragma warning restore CS1591
    }
}
