// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.OpenAI.OpenApiClient.Models
{
    /// <summary>
    /// Multipart parameters for extending an existing generated video.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CreateVideoExtendMultipartBody : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Updated text prompt that directs the extension generation.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Prompt { get; set; }
#nullable restore
#else
        public string Prompt { get; set; }
#endif
        /// <summary>Length of the newly generated extension segment in seconds (allowed values: 4, 8, 12, 16, 20).</summary>
        public global::Soenneker.OpenAI.OpenApiClient.Models.VideoSeconds? Seconds { get; set; }
        /// <summary>The video property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.CreateVideoExtendMultipartBody.CreateVideoExtendMultipartBody_video? Video { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.CreateVideoExtendMultipartBody.CreateVideoExtendMultipartBody_video Video { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.CreateVideoExtendMultipartBody"/> and sets the default values.
        /// </summary>
        public CreateVideoExtendMultipartBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.CreateVideoExtendMultipartBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.OpenAI.OpenApiClient.Models.CreateVideoExtendMultipartBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.OpenAI.OpenApiClient.Models.CreateVideoExtendMultipartBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "prompt", n => { Prompt = n.GetStringValue(); } },
                { "seconds", n => { Seconds = n.GetEnumValue<global::Soenneker.OpenAI.OpenApiClient.Models.VideoSeconds>(); } },
                { "video", n => { Video = n.GetObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.CreateVideoExtendMultipartBody.CreateVideoExtendMultipartBody_video>(global::Soenneker.OpenAI.OpenApiClient.Models.CreateVideoExtendMultipartBody.CreateVideoExtendMultipartBody_video.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("prompt", Prompt);
            writer.WriteEnumValue<global::Soenneker.OpenAI.OpenApiClient.Models.VideoSeconds>("seconds", Seconds);
            writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.CreateVideoExtendMultipartBody.CreateVideoExtendMultipartBody_video>("video", Video);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="byte[]"/>, <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.VideoReferenceInputParam"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CreateVideoExtendMultipartBody_video : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="byte[]"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public byte[]? Binary { get; set; }
#nullable restore
#else
            public byte[] Binary { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.VideoReferenceInputParam"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.OpenAI.OpenApiClient.Models.VideoReferenceInputParam? VideoReferenceInputParam { get; set; }
#nullable restore
#else
            public global::Soenneker.OpenAI.OpenApiClient.Models.VideoReferenceInputParam VideoReferenceInputParam { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.CreateVideoExtendMultipartBody.CreateVideoExtendMultipartBody_video"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.OpenAI.OpenApiClient.Models.CreateVideoExtendMultipartBody.CreateVideoExtendMultipartBody_video CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::Soenneker.OpenAI.OpenApiClient.Models.CreateVideoExtendMultipartBody.CreateVideoExtendMultipartBody_video();
                if("VideoReferenceInputParam".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.VideoReferenceInputParam = new global::Soenneker.OpenAI.OpenApiClient.Models.VideoReferenceInputParam();
                }
                else if(parseNode.GetByteArrayValue() is byte[] binaryValue)
                {
                    result.Binary = binaryValue;
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(VideoReferenceInputParam != null)
                {
                    return VideoReferenceInputParam.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(VideoReferenceInputParam != null)
                {
                    writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.VideoReferenceInputParam>(null, VideoReferenceInputParam);
                }
                else if(Binary != null)
                {
                    writer.WriteByteArrayValue(null, Binary);
                }
            }
        }
    }
}
#pragma warning restore CS0618
