// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.OpenAI.OpenApiClient.Models
{
    /// <summary>
    /// Uploads a new immutable version of a skill.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CreateSkillVersionBody : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Whether to set this version as the default.</summary>
        public bool? Default { get; set; }
        /// <summary>The files property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.CreateSkillVersionBody.CreateSkillVersionBody_files? Files { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.CreateSkillVersionBody.CreateSkillVersionBody_files Files { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.CreateSkillVersionBody"/> and sets the default values.
        /// </summary>
        public CreateSkillVersionBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.CreateSkillVersionBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.OpenAI.OpenApiClient.Models.CreateSkillVersionBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.OpenAI.OpenApiClient.Models.CreateSkillVersionBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "default", n => { Default = n.GetBoolValue(); } },
                { "files", n => { Files = n.GetObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.CreateSkillVersionBody.CreateSkillVersionBody_files>(global::Soenneker.OpenAI.OpenApiClient.Models.CreateSkillVersionBody.CreateSkillVersionBody_files.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("default", Default);
            writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.CreateSkillVersionBody.CreateSkillVersionBody_files>("files", Files);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="byte[]"/>, List&lt;byte[]&gt;
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CreateSkillVersionBody_files : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type List&lt;byte[]&gt;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public List<byte[]>? Binary { get; set; }
#nullable restore
#else
            public List<byte[]> Binary { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="byte[]"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public byte[]? CreateSkillVersionBodyFilesBinary { get; set; }
#nullable restore
#else
            public byte[] CreateSkillVersionBodyFilesBinary { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.CreateSkillVersionBody.CreateSkillVersionBody_files"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.OpenAI.OpenApiClient.Models.CreateSkillVersionBody.CreateSkillVersionBody_files CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::Soenneker.OpenAI.OpenApiClient.Models.CreateSkillVersionBody.CreateSkillVersionBody_files();
                if(parseNode.GetByteArrayValue() is byte[] createSkillVersionBodyFilesBinaryValue)
                {
                    result.CreateSkillVersionBodyFilesBinary = createSkillVersionBodyFilesBinaryValue;
                }
                else if(parseNode.GetCollectionOfPrimitiveValues<byte[]>()?.AsList() is List<byte[]> binaryValue)
                {
                    result.Binary = binaryValue;
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(CreateSkillVersionBodyFilesBinary != null)
                {
                    writer.WriteByteArrayValue(null, CreateSkillVersionBodyFilesBinary);
                }
                else if(Binary != null)
                {
                    writer.WriteCollectionOfPrimitiveValues<byte[]>(null, Binary);
                }
            }
        }
    }
}
#pragma warning restore CS0618
