// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.OpenAI.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum DeletedConversationResource_object
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "conversation.deleted")]
        #pragma warning disable CS1591
        ConversationDeleted,
        #pragma warning restore CS1591
    }
}
