// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.OpenAI.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.EnvironmentResourceNone"/>, <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.EnvironmentResourceOpenaiHosted"/>, <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.EnvironmentResourceSelfHosted"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class EnvironmentResource : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.EnvironmentResourceNone"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.EnvironmentResourceNone? EnvironmentResourceNone { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.EnvironmentResourceNone EnvironmentResourceNone { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.EnvironmentResourceOpenaiHosted"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.EnvironmentResourceOpenaiHosted? EnvironmentResourceOpenaiHosted { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.EnvironmentResourceOpenaiHosted EnvironmentResourceOpenaiHosted { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.EnvironmentResourceSelfHosted"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.EnvironmentResourceSelfHosted? EnvironmentResourceSelfHosted { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.EnvironmentResourceSelfHosted EnvironmentResourceSelfHosted { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.EnvironmentResource"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.OpenAI.OpenApiClient.Models.EnvironmentResource CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            var result = new global::Soenneker.OpenAI.OpenApiClient.Models.EnvironmentResource();
            if("EnvironmentResourceNone".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.EnvironmentResourceNone = new global::Soenneker.OpenAI.OpenApiClient.Models.EnvironmentResourceNone();
            }
            else if("EnvironmentResourceOpenaiHosted".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.EnvironmentResourceOpenaiHosted = new global::Soenneker.OpenAI.OpenApiClient.Models.EnvironmentResourceOpenaiHosted();
            }
            else if("EnvironmentResourceSelfHosted".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.EnvironmentResourceSelfHosted = new global::Soenneker.OpenAI.OpenApiClient.Models.EnvironmentResourceSelfHosted();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(EnvironmentResourceNone != null)
            {
                return EnvironmentResourceNone.GetFieldDeserializers();
            }
            else if(EnvironmentResourceOpenaiHosted != null)
            {
                return EnvironmentResourceOpenaiHosted.GetFieldDeserializers();
            }
            else if(EnvironmentResourceSelfHosted != null)
            {
                return EnvironmentResourceSelfHosted.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(EnvironmentResourceNone != null)
            {
                writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.EnvironmentResourceNone>(null, EnvironmentResourceNone);
            }
            else if(EnvironmentResourceOpenaiHosted != null)
            {
                writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.EnvironmentResourceOpenaiHosted>(null, EnvironmentResourceOpenaiHosted);
            }
            else if(EnvironmentResourceSelfHosted != null)
            {
                writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.EnvironmentResourceSelfHosted>(null, EnvironmentResourceSelfHosted);
            }
        }
    }
}
#pragma warning restore CS0618
