// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.OpenAI.OpenApiClient.Models
{
    /// <summary>
    /// A sample containing the input and output of the evaluation run.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class EvalRunOutputItemSample : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>An object representing an error response from the Eval API.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.EvalApiError? Error { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.EvalApiError Error { get; set; }
#endif
        /// <summary>The reason why the sample generation was finished.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FinishReason { get; set; }
#nullable restore
#else
        public string FinishReason { get; set; }
#endif
        /// <summary>An array of input messages.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.OpenAI.OpenApiClient.Models.EvalRunOutputItemSampleInputItem>? Input { get; set; }
#nullable restore
#else
        public List<global::Soenneker.OpenAI.OpenApiClient.Models.EvalRunOutputItemSampleInputItem> Input { get; set; }
#endif
        /// <summary>The maximum number of tokens allowed for completion.</summary>
        public int? MaxCompletionTokens { get; set; }
        /// <summary>The model used for generating the sample.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Model { get; set; }
#nullable restore
#else
        public string Model { get; set; }
#endif
        /// <summary>An array of output messages.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.OpenAI.OpenApiClient.Models.EvalRunOutputItemSampleOutputItem>? Output { get; set; }
#nullable restore
#else
        public List<global::Soenneker.OpenAI.OpenApiClient.Models.EvalRunOutputItemSampleOutputItem> Output { get; set; }
#endif
        /// <summary>The seed used for generating the sample.</summary>
        public int? Seed { get; set; }
        /// <summary>The sampling temperature used.</summary>
        public double? Temperature { get; set; }
        /// <summary>The top_p value used for sampling.</summary>
        public double? TopP { get; set; }
        /// <summary>Token usage details for the sample.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.EvalRunOutputItemSampleUsage? Usage { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.EvalRunOutputItemSampleUsage Usage { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.EvalRunOutputItemSample"/> and sets the default values.
        /// </summary>
        public EvalRunOutputItemSample()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.EvalRunOutputItemSample"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.OpenAI.OpenApiClient.Models.EvalRunOutputItemSample CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.OpenAI.OpenApiClient.Models.EvalRunOutputItemSample();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "error", n => { Error = n.GetObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.EvalApiError>(global::Soenneker.OpenAI.OpenApiClient.Models.EvalApiError.CreateFromDiscriminatorValue); } },
                { "finish_reason", n => { FinishReason = n.GetStringValue(); } },
                { "input", n => { Input = n.GetCollectionOfObjectValues<global::Soenneker.OpenAI.OpenApiClient.Models.EvalRunOutputItemSampleInputItem>(global::Soenneker.OpenAI.OpenApiClient.Models.EvalRunOutputItemSampleInputItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "max_completion_tokens", n => { MaxCompletionTokens = n.GetIntValue(); } },
                { "model", n => { Model = n.GetStringValue(); } },
                { "output", n => { Output = n.GetCollectionOfObjectValues<global::Soenneker.OpenAI.OpenApiClient.Models.EvalRunOutputItemSampleOutputItem>(global::Soenneker.OpenAI.OpenApiClient.Models.EvalRunOutputItemSampleOutputItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "seed", n => { Seed = n.GetIntValue(); } },
                { "temperature", n => { Temperature = n.GetDoubleValue(); } },
                { "top_p", n => { TopP = n.GetDoubleValue(); } },
                { "usage", n => { Usage = n.GetObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.EvalRunOutputItemSampleUsage>(global::Soenneker.OpenAI.OpenApiClient.Models.EvalRunOutputItemSampleUsage.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.EvalApiError>("error", Error);
            writer.WriteStringValue("finish_reason", FinishReason);
            writer.WriteCollectionOfObjectValues<global::Soenneker.OpenAI.OpenApiClient.Models.EvalRunOutputItemSampleInputItem>("input", Input);
            writer.WriteIntValue("max_completion_tokens", MaxCompletionTokens);
            writer.WriteStringValue("model", Model);
            writer.WriteCollectionOfObjectValues<global::Soenneker.OpenAI.OpenApiClient.Models.EvalRunOutputItemSampleOutputItem>("output", Output);
            writer.WriteIntValue("seed", Seed);
            writer.WriteDoubleValue("temperature", Temperature);
            writer.WriteDoubleValue("top_p", TopP);
            writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.EvalRunOutputItemSampleUsage>("usage", Usage);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
