// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.OpenAI.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class FunctionToolParam : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The allowed_callers property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.FunctionToolParamAllowedCallers? AllowedCallers { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.FunctionToolParamAllowedCallers AllowedCallers { get; set; }
#endif
        /// <summary>Whether this function should be deferred and discovered via tool search.</summary>
        public bool? DeferLoading { get; set; }
        /// <summary>The description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.FunctionToolParamDescription? Description { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.FunctionToolParamDescription Description { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The output_schema property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.FunctionToolParamOutputSchema? OutputSchema { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.FunctionToolParamOutputSchema OutputSchema { get; set; }
#endif
        /// <summary>The parameters property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.FunctionToolParamParameters? Parameters { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.FunctionToolParamParameters Parameters { get; set; }
#endif
        /// <summary>The strict property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.FunctionToolParamStrict? Strict { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.FunctionToolParamStrict Strict { get; set; }
#endif
        /// <summary>The type property</summary>
        public global::Soenneker.OpenAI.OpenApiClient.Models.FunctionToolParamType? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.FunctionToolParam"/> and sets the default values.
        /// </summary>
        public FunctionToolParam()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.FunctionToolParam"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.OpenAI.OpenApiClient.Models.FunctionToolParam CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.OpenAI.OpenApiClient.Models.FunctionToolParam();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "allowed_callers", n => { AllowedCallers = n.GetObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.FunctionToolParamAllowedCallers>(global::Soenneker.OpenAI.OpenApiClient.Models.FunctionToolParamAllowedCallers.CreateFromDiscriminatorValue); } },
                { "defer_loading", n => { DeferLoading = n.GetBoolValue(); } },
                { "description", n => { Description = n.GetObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.FunctionToolParamDescription>(global::Soenneker.OpenAI.OpenApiClient.Models.FunctionToolParamDescription.CreateFromDiscriminatorValue); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "output_schema", n => { OutputSchema = n.GetObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.FunctionToolParamOutputSchema>(global::Soenneker.OpenAI.OpenApiClient.Models.FunctionToolParamOutputSchema.CreateFromDiscriminatorValue); } },
                { "parameters", n => { Parameters = n.GetObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.FunctionToolParamParameters>(global::Soenneker.OpenAI.OpenApiClient.Models.FunctionToolParamParameters.CreateFromDiscriminatorValue); } },
                { "strict", n => { Strict = n.GetObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.FunctionToolParamStrict>(global::Soenneker.OpenAI.OpenApiClient.Models.FunctionToolParamStrict.CreateFromDiscriminatorValue); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.OpenAI.OpenApiClient.Models.FunctionToolParamType>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.FunctionToolParamAllowedCallers>("allowed_callers", AllowedCallers);
            writer.WriteBoolValue("defer_loading", DeferLoading);
            writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.FunctionToolParamDescription>("description", Description);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.FunctionToolParamOutputSchema>("output_schema", OutputSchema);
            writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.FunctionToolParamParameters>("parameters", Parameters);
            writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.FunctionToolParamStrict>("strict", Strict);
            writer.WriteEnumValue<global::Soenneker.OpenAI.OpenApiClient.Models.FunctionToolParamType>("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
