// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.OpenAI.OpenApiClient.Models
{
    /// <summary>The object type, which is always `python`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum GraderPython_type
    {
        [EnumMember(Value = "python")]
        #pragma warning disable CS1591
        Python,
        #pragma warning restore CS1591
    }
}
