// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.OpenAI.OpenApiClient.Models
{
    /// <summary>
    /// The sampling parameters for the model.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GraderScoreModelSamplingParams : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The max_completions_tokens property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.GraderScoreModelSamplingParams_max_completions_tokens? MaxCompletionsTokens { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.GraderScoreModelSamplingParams_max_completions_tokens MaxCompletionsTokens { get; set; }
#endif
        /// <summary>The reasoning_effort property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.ReasoningEffort? ReasoningEffort { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.ReasoningEffort ReasoningEffort { get; set; }
#endif
        /// <summary>The seed property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.GraderScoreModelSamplingParams_seed? Seed { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.GraderScoreModelSamplingParams_seed Seed { get; set; }
#endif
        /// <summary>The temperature property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.GraderScoreModelSamplingParams_temperature? Temperature { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.GraderScoreModelSamplingParams_temperature Temperature { get; set; }
#endif
        /// <summary>The top_p property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.GraderScoreModelSamplingParams_top_p? TopP { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.GraderScoreModelSamplingParams_top_p TopP { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.GraderScoreModelSamplingParams"/> and sets the default values.
        /// </summary>
        public GraderScoreModelSamplingParams()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.GraderScoreModelSamplingParams"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.OpenAI.OpenApiClient.Models.GraderScoreModelSamplingParams CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.OpenAI.OpenApiClient.Models.GraderScoreModelSamplingParams();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "max_completions_tokens", n => { MaxCompletionsTokens = n.GetObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.GraderScoreModelSamplingParams_max_completions_tokens>(global::Soenneker.OpenAI.OpenApiClient.Models.GraderScoreModelSamplingParams_max_completions_tokens.CreateFromDiscriminatorValue); } },
                { "reasoning_effort", n => { ReasoningEffort = n.GetObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.ReasoningEffort>(global::Soenneker.OpenAI.OpenApiClient.Models.ReasoningEffort.CreateFromDiscriminatorValue); } },
                { "seed", n => { Seed = n.GetObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.GraderScoreModelSamplingParams_seed>(global::Soenneker.OpenAI.OpenApiClient.Models.GraderScoreModelSamplingParams_seed.CreateFromDiscriminatorValue); } },
                { "temperature", n => { Temperature = n.GetObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.GraderScoreModelSamplingParams_temperature>(global::Soenneker.OpenAI.OpenApiClient.Models.GraderScoreModelSamplingParams_temperature.CreateFromDiscriminatorValue); } },
                { "top_p", n => { TopP = n.GetObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.GraderScoreModelSamplingParams_top_p>(global::Soenneker.OpenAI.OpenApiClient.Models.GraderScoreModelSamplingParams_top_p.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.GraderScoreModelSamplingParams_max_completions_tokens>("max_completions_tokens", MaxCompletionsTokens);
            writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.ReasoningEffort>("reasoning_effort", ReasoningEffort);
            writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.GraderScoreModelSamplingParams_seed>("seed", Seed);
            writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.GraderScoreModelSamplingParams_temperature>("temperature", Temperature);
            writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.GraderScoreModelSamplingParams_top_p>("top_p", TopP);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
