// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.OpenAI.OpenApiClient.Models
{
    /// <summary>The media type of the inline skill payload. Must be `application/zip`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum InlineSkillSourceParam_media_type
    {
        [EnumMember(Value = "application/zip")]
        #pragma warning disable CS1591
        ApplicationZip,
        #pragma warning restore CS1591
    }
}
