// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.OpenAI.OpenApiClient.Models
{
    /// <summary>The object type, which is always `organization.invite`</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Invite_object
    {
        [EnumMember(Value = "organization.invite")]
        #pragma warning disable CS1591
        OrganizationInvite,
        #pragma warning restore CS1591
    }
}
