// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.OpenAI.OpenApiClient.Models
{
    /// <summary>Project membership role</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Invite_projects_role
    {
        [EnumMember(Value = "member")]
        #pragma warning disable CS1591
        Member,
        #pragma warning restore CS1591
        [EnumMember(Value = "owner")]
        #pragma warning disable CS1591
        Owner,
        #pragma warning restore CS1591
    }
}
