// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.OpenAI.OpenApiClient.Models
{
    /// <summary>The session type. Always `live`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum LiveType
    {
        [EnumMember(Value = "live")]
        #pragma warning disable CS1591
        Live,
        #pragma warning restore CS1591
    }
}
