// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.OpenAI.OpenApiClient.Models
{
    /// <summary>The type of the event. Always `live.call.incoming`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum LiveCallIncomingType
    {
        [EnumMember(Value = "live.call.incoming")]
        #pragma warning disable CS1591
        LiveCallIncoming,
        #pragma warning restore CS1591
    }
}
