// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.OpenAI.OpenApiClient.Models
{
    /// <summary>
    /// Model, prompt, and tool settings for tasks delegated by the Live session to a Responses backend.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class LiveResponsesDelegationSettingsInputParam : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Instructions for the delegated Responses model, separate from Live instructions. See [backend prompting](https://developers.openai.com/api/docs/guides/live-delegation#start-with-your-existing-backend-prompt).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Instructions { get; set; }
#nullable restore
#else
        public string Instructions { get; set; }
#endif
        /// <summary>Maximum number of output tokens for each delegated response.</summary>
        public int? MaxOutputTokens { get; set; }
        /// <summary>The model used for server-owned Responses delegations.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Model { get; set; }
#nullable restore
#else
        public string Model { get; set; }
#endif
        /// <summary>Whether the delegated Responses model may request multiple tool calls in a single response.</summary>
        public bool? ParallelToolCalls { get; set; }
        /// <summary>The reasoning property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.LiveDelegationReasoningInputParam? Reasoning { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.LiveDelegationReasoningInputParam Reasoning { get; set; }
#endif
        /// <summary>The service_tier property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.LiveResponsesServiceTierWrapper? ServiceTier { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.LiveResponsesServiceTierWrapper ServiceTier { get; set; }
#endif
        /// <summary>The text property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.LiveDelegationTextInputParam? Text { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.LiveDelegationTextInputParam Text { get; set; }
#endif
        /// <summary>Controls which tool the Responses backend uses when handling a task delegated by the Live model.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.LiveResponsesDelegationSettingsInputParamToolChoice? ToolChoice { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.LiveResponsesDelegationSettingsInputParamToolChoice ToolChoice { get; set; }
#endif
        /// <summary>Tools available to the Responses backend while it handles tasks delegated by the Live model.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.OpenAI.OpenApiClient.Models.LiveResponsesDelegationSettingsInputParamToolsItem>? Tools { get; set; }
#nullable restore
#else
        public List<global::Soenneker.OpenAI.OpenApiClient.Models.LiveResponsesDelegationSettingsInputParamToolsItem> Tools { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.LiveResponsesDelegationSettingsInputParam"/> and sets the default values.
        /// </summary>
        public LiveResponsesDelegationSettingsInputParam()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.LiveResponsesDelegationSettingsInputParam"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.OpenAI.OpenApiClient.Models.LiveResponsesDelegationSettingsInputParam CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.OpenAI.OpenApiClient.Models.LiveResponsesDelegationSettingsInputParam();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "instructions", n => { Instructions = n.GetStringValue(); } },
                { "max_output_tokens", n => { MaxOutputTokens = n.GetIntValue(); } },
                { "model", n => { Model = n.GetStringValue(); } },
                { "parallel_tool_calls", n => { ParallelToolCalls = n.GetBoolValue(); } },
                { "reasoning", n => { Reasoning = n.GetObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.LiveDelegationReasoningInputParam>(global::Soenneker.OpenAI.OpenApiClient.Models.LiveDelegationReasoningInputParam.CreateFromDiscriminatorValue); } },
                { "service_tier", n => { ServiceTier = n.GetObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.LiveResponsesServiceTierWrapper>(global::Soenneker.OpenAI.OpenApiClient.Models.LiveResponsesServiceTierWrapper.CreateFromDiscriminatorValue); } },
                { "text", n => { Text = n.GetObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.LiveDelegationTextInputParam>(global::Soenneker.OpenAI.OpenApiClient.Models.LiveDelegationTextInputParam.CreateFromDiscriminatorValue); } },
                { "tool_choice", n => { ToolChoice = n.GetObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.LiveResponsesDelegationSettingsInputParamToolChoice>(global::Soenneker.OpenAI.OpenApiClient.Models.LiveResponsesDelegationSettingsInputParamToolChoice.CreateFromDiscriminatorValue); } },
                { "tools", n => { Tools = n.GetCollectionOfObjectValues<global::Soenneker.OpenAI.OpenApiClient.Models.LiveResponsesDelegationSettingsInputParamToolsItem>(global::Soenneker.OpenAI.OpenApiClient.Models.LiveResponsesDelegationSettingsInputParamToolsItem.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("instructions", Instructions);
            writer.WriteIntValue("max_output_tokens", MaxOutputTokens);
            writer.WriteStringValue("model", Model);
            writer.WriteBoolValue("parallel_tool_calls", ParallelToolCalls);
            writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.LiveDelegationReasoningInputParam>("reasoning", Reasoning);
            writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.LiveResponsesServiceTierWrapper>("service_tier", ServiceTier);
            writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.LiveDelegationTextInputParam>("text", Text);
            writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.LiveResponsesDelegationSettingsInputParamToolChoice>("tool_choice", ToolChoice);
            writer.WriteCollectionOfObjectValues<global::Soenneker.OpenAI.OpenApiClient.Models.LiveResponsesDelegationSettingsInputParamToolsItem>("tools", Tools);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
