// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.OpenAI.OpenApiClient.Models
{
    /// <summary>
    /// A message to or from the model.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Message : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The content of the message</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.OpenAI.OpenApiClient.Models.Message.Message_content>? Content { get; set; }
#nullable restore
#else
        public List<global::Soenneker.OpenAI.OpenApiClient.Models.Message.Message_content> Content { get; set; }
#endif
        /// <summary>The unique ID of the message.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The phase property</summary>
        public global::Soenneker.OpenAI.OpenApiClient.Models.MessagePhase2? Phase { get; set; }
        /// <summary>The role of the message. One of `unknown`, `user`, `assistant`, `system`, `critic`, `discriminator`, `developer`, or `tool`.</summary>
        public global::Soenneker.OpenAI.OpenApiClient.Models.MessageRole? Role { get; set; }
        /// <summary>The status of item. One of `in_progress`, `completed`, or `incomplete`. Populated when items are returned via API.</summary>
        public global::Soenneker.OpenAI.OpenApiClient.Models.MessageStatus? Status { get; set; }
        /// <summary>The type of the message. Always set to `message`.</summary>
        public global::Soenneker.OpenAI.OpenApiClient.Models.Message_type? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.Message"/> and sets the default values.
        /// </summary>
        public Message()
        {
            AdditionalData = new Dictionary<string, object>();
            Type = global::Soenneker.OpenAI.OpenApiClient.Models.Message_type.Message;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.Message"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.OpenAI.OpenApiClient.Models.Message CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.OpenAI.OpenApiClient.Models.Message();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "content", n => { Content = n.GetCollectionOfObjectValues<global::Soenneker.OpenAI.OpenApiClient.Models.Message.Message_content>(global::Soenneker.OpenAI.OpenApiClient.Models.Message.Message_content.CreateFromDiscriminatorValue)?.AsList(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "phase", n => { Phase = n.GetEnumValue<global::Soenneker.OpenAI.OpenApiClient.Models.MessagePhase2>(); } },
                { "role", n => { Role = n.GetEnumValue<global::Soenneker.OpenAI.OpenApiClient.Models.MessageRole>(); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.OpenAI.OpenApiClient.Models.MessageStatus>(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.OpenAI.OpenApiClient.Models.Message_type>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.OpenAI.OpenApiClient.Models.Message.Message_content>("content", Content);
            writer.WriteStringValue("id", Id);
            writer.WriteEnumValue<global::Soenneker.OpenAI.OpenApiClient.Models.MessagePhase2>("phase", Phase);
            writer.WriteEnumValue<global::Soenneker.OpenAI.OpenApiClient.Models.MessageRole>("role", Role);
            writer.WriteEnumValue<global::Soenneker.OpenAI.OpenApiClient.Models.MessageStatus>("status", Status);
            writer.WriteEnumValue<global::Soenneker.OpenAI.OpenApiClient.Models.Message_type>("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.ComputerScreenshotContent"/>, <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.InputFileContent"/>, <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.InputImageContent"/>, <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.InputTextContent"/>, <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.OutputTextContent"/>, <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.ReasoningTextContent"/>, <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.RefusalContent"/>, <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.SummaryTextContent"/>, <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.TextContent"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Message_content : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.ComputerScreenshotContent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.OpenAI.OpenApiClient.Models.ComputerScreenshotContent? ComputerScreenshotContent { get; set; }
#nullable restore
#else
            public global::Soenneker.OpenAI.OpenApiClient.Models.ComputerScreenshotContent ComputerScreenshotContent { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.InputFileContent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.OpenAI.OpenApiClient.Models.InputFileContent? InputFileContent { get; set; }
#nullable restore
#else
            public global::Soenneker.OpenAI.OpenApiClient.Models.InputFileContent InputFileContent { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.InputImageContent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.OpenAI.OpenApiClient.Models.InputImageContent? InputImageContent { get; set; }
#nullable restore
#else
            public global::Soenneker.OpenAI.OpenApiClient.Models.InputImageContent InputImageContent { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.InputTextContent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.OpenAI.OpenApiClient.Models.InputTextContent? InputTextContent { get; set; }
#nullable restore
#else
            public global::Soenneker.OpenAI.OpenApiClient.Models.InputTextContent InputTextContent { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.OutputTextContent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.OpenAI.OpenApiClient.Models.OutputTextContent? OutputTextContent { get; set; }
#nullable restore
#else
            public global::Soenneker.OpenAI.OpenApiClient.Models.OutputTextContent OutputTextContent { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.ReasoningTextContent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.OpenAI.OpenApiClient.Models.ReasoningTextContent? ReasoningTextContent { get; set; }
#nullable restore
#else
            public global::Soenneker.OpenAI.OpenApiClient.Models.ReasoningTextContent ReasoningTextContent { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.RefusalContent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.OpenAI.OpenApiClient.Models.RefusalContent? RefusalContent { get; set; }
#nullable restore
#else
            public global::Soenneker.OpenAI.OpenApiClient.Models.RefusalContent RefusalContent { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.SummaryTextContent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.OpenAI.OpenApiClient.Models.SummaryTextContent? SummaryTextContent { get; set; }
#nullable restore
#else
            public global::Soenneker.OpenAI.OpenApiClient.Models.SummaryTextContent SummaryTextContent { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.TextContent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.OpenAI.OpenApiClient.Models.TextContent? TextContent { get; set; }
#nullable restore
#else
            public global::Soenneker.OpenAI.OpenApiClient.Models.TextContent TextContent { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.Message.Message_content"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.OpenAI.OpenApiClient.Models.Message.Message_content CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
                var result = new global::Soenneker.OpenAI.OpenApiClient.Models.Message.Message_content();
                if("ComputerScreenshotContent".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.ComputerScreenshotContent = new global::Soenneker.OpenAI.OpenApiClient.Models.ComputerScreenshotContent();
                }
                else if("InputFileContent".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.InputFileContent = new global::Soenneker.OpenAI.OpenApiClient.Models.InputFileContent();
                }
                else if("InputImageContent".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.InputImageContent = new global::Soenneker.OpenAI.OpenApiClient.Models.InputImageContent();
                }
                else if("InputTextContent".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.InputTextContent = new global::Soenneker.OpenAI.OpenApiClient.Models.InputTextContent();
                }
                else if("OutputTextContent".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.OutputTextContent = new global::Soenneker.OpenAI.OpenApiClient.Models.OutputTextContent();
                }
                else if("ReasoningTextContent".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.ReasoningTextContent = new global::Soenneker.OpenAI.OpenApiClient.Models.ReasoningTextContent();
                }
                else if("RefusalContent".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.RefusalContent = new global::Soenneker.OpenAI.OpenApiClient.Models.RefusalContent();
                }
                else if("SummaryTextContent".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.SummaryTextContent = new global::Soenneker.OpenAI.OpenApiClient.Models.SummaryTextContent();
                }
                else if("TextContent".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.TextContent = new global::Soenneker.OpenAI.OpenApiClient.Models.TextContent();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ComputerScreenshotContent != null)
                {
                    return ComputerScreenshotContent.GetFieldDeserializers();
                }
                else if(InputFileContent != null)
                {
                    return InputFileContent.GetFieldDeserializers();
                }
                else if(InputImageContent != null)
                {
                    return InputImageContent.GetFieldDeserializers();
                }
                else if(InputTextContent != null)
                {
                    return InputTextContent.GetFieldDeserializers();
                }
                else if(OutputTextContent != null)
                {
                    return OutputTextContent.GetFieldDeserializers();
                }
                else if(ReasoningTextContent != null)
                {
                    return ReasoningTextContent.GetFieldDeserializers();
                }
                else if(RefusalContent != null)
                {
                    return RefusalContent.GetFieldDeserializers();
                }
                else if(SummaryTextContent != null)
                {
                    return SummaryTextContent.GetFieldDeserializers();
                }
                else if(TextContent != null)
                {
                    return TextContent.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(ComputerScreenshotContent != null)
                {
                    writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.ComputerScreenshotContent>(null, ComputerScreenshotContent);
                }
                else if(InputFileContent != null)
                {
                    writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.InputFileContent>(null, InputFileContent);
                }
                else if(InputImageContent != null)
                {
                    writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.InputImageContent>(null, InputImageContent);
                }
                else if(InputTextContent != null)
                {
                    writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.InputTextContent>(null, InputTextContent);
                }
                else if(OutputTextContent != null)
                {
                    writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.OutputTextContent>(null, OutputTextContent);
                }
                else if(ReasoningTextContent != null)
                {
                    writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.ReasoningTextContent>(null, ReasoningTextContent);
                }
                else if(RefusalContent != null)
                {
                    writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.RefusalContent>(null, RefusalContent);
                }
                else if(SummaryTextContent != null)
                {
                    writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.SummaryTextContent>(null, SummaryTextContent);
                }
                else if(TextContent != null)
                {
                    writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.TextContent>(null, TextContent);
                }
            }
        }
    }
}
#pragma warning restore CS0618
