// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.OpenAI.OpenApiClient.Models
{
    /// <summary>The type of the output text. Always `output_text`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum OutputTextContent_type
    {
        [EnumMember(Value = "output_text")]
        #pragma warning disable CS1591
        Output_text,
        #pragma warning restore CS1591
    }
}
