// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.OpenAI.OpenApiClient.Models
{
    /// <summary>The model permissions mode to apply.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ProjectModelPermissionsUpdateRequestMode
    {
        [EnumMember(Value = "allow_list")]
        #pragma warning disable CS1591
        AllowList,
        #pragma warning restore CS1591
        [EnumMember(Value = "deny_list")]
        #pragma warning disable CS1591
        DenyList,
        #pragma warning restore CS1591
    }
}
