// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.OpenAI.OpenApiClient.Models
{
    /// <summary>The configured project data retention type.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ProjectDataRetention_type
    {
        [EnumMember(Value = "organization_default")]
        #pragma warning disable CS1591
        Organization_default,
        #pragma warning restore CS1591
        [EnumMember(Value = "none")]
        #pragma warning disable CS1591
        None,
        #pragma warning restore CS1591
        [EnumMember(Value = "zero_data_retention")]
        #pragma warning disable CS1591
        Zero_data_retention,
        #pragma warning restore CS1591
        [EnumMember(Value = "modified_abuse_monitoring")]
        #pragma warning disable CS1591
        Modified_abuse_monitoring,
        #pragma warning restore CS1591
        [EnumMember(Value = "enhanced_zero_data_retention")]
        #pragma warning disable CS1591
        Enhanced_zero_data_retention,
        #pragma warning restore CS1591
        [EnumMember(Value = "enhanced_modified_abuse_monitoring")]
        #pragma warning disable CS1591
        Enhanced_modified_abuse_monitoring,
        #pragma warning restore CS1591
    }
}
