// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.OpenAI.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum PromptCacheRetentionEnum
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "in_memory")]
        #pragma warning disable CS1591
        InMemory,
        #pragma warning restore CS1591
        [EnumMember(Value = "24h")]
        #pragma warning disable CS1591
        Value24H,
        #pragma warning restore CS1591
    }
}
