// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.OpenAI.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.PromptCacheComparisonResponseNotFoundDiagnosticsBody"/>, <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.PromptCacheHitDiagnosticsBody"/>, <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.PromptCacheMissDiagnosticsBody"/>, <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.PromptCacheUnavailableDiagnosticsBody"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PromptCacheDiagnostics : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.PromptCacheComparisonResponseNotFoundDiagnosticsBody"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.PromptCacheComparisonResponseNotFoundDiagnosticsBody? PromptCacheComparisonResponseNotFoundDiagnosticsBody { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.PromptCacheComparisonResponseNotFoundDiagnosticsBody PromptCacheComparisonResponseNotFoundDiagnosticsBody { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.PromptCacheHitDiagnosticsBody"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.PromptCacheHitDiagnosticsBody? PromptCacheHitDiagnosticsBody { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.PromptCacheHitDiagnosticsBody PromptCacheHitDiagnosticsBody { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.PromptCacheMissDiagnosticsBody"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.PromptCacheMissDiagnosticsBody? PromptCacheMissDiagnosticsBody { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.PromptCacheMissDiagnosticsBody PromptCacheMissDiagnosticsBody { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.PromptCacheUnavailableDiagnosticsBody"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.PromptCacheUnavailableDiagnosticsBody? PromptCacheUnavailableDiagnosticsBody { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.PromptCacheUnavailableDiagnosticsBody PromptCacheUnavailableDiagnosticsBody { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.PromptCacheDiagnostics"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.OpenAI.OpenApiClient.Models.PromptCacheDiagnostics CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            var result = new global::Soenneker.OpenAI.OpenApiClient.Models.PromptCacheDiagnostics();
            if("PromptCacheComparisonResponseNotFoundDiagnosticsBody".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.PromptCacheComparisonResponseNotFoundDiagnosticsBody = new global::Soenneker.OpenAI.OpenApiClient.Models.PromptCacheComparisonResponseNotFoundDiagnosticsBody();
            }
            else if("PromptCacheHitDiagnosticsBody".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.PromptCacheHitDiagnosticsBody = new global::Soenneker.OpenAI.OpenApiClient.Models.PromptCacheHitDiagnosticsBody();
            }
            else if("PromptCacheMissDiagnosticsBody".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.PromptCacheMissDiagnosticsBody = new global::Soenneker.OpenAI.OpenApiClient.Models.PromptCacheMissDiagnosticsBody();
            }
            else if("PromptCacheUnavailableDiagnosticsBody".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.PromptCacheUnavailableDiagnosticsBody = new global::Soenneker.OpenAI.OpenApiClient.Models.PromptCacheUnavailableDiagnosticsBody();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(PromptCacheComparisonResponseNotFoundDiagnosticsBody != null)
            {
                return PromptCacheComparisonResponseNotFoundDiagnosticsBody.GetFieldDeserializers();
            }
            else if(PromptCacheHitDiagnosticsBody != null)
            {
                return PromptCacheHitDiagnosticsBody.GetFieldDeserializers();
            }
            else if(PromptCacheMissDiagnosticsBody != null)
            {
                return PromptCacheMissDiagnosticsBody.GetFieldDeserializers();
            }
            else if(PromptCacheUnavailableDiagnosticsBody != null)
            {
                return PromptCacheUnavailableDiagnosticsBody.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(PromptCacheComparisonResponseNotFoundDiagnosticsBody != null)
            {
                writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.PromptCacheComparisonResponseNotFoundDiagnosticsBody>(null, PromptCacheComparisonResponseNotFoundDiagnosticsBody);
            }
            else if(PromptCacheHitDiagnosticsBody != null)
            {
                writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.PromptCacheHitDiagnosticsBody>(null, PromptCacheHitDiagnosticsBody);
            }
            else if(PromptCacheMissDiagnosticsBody != null)
            {
                writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.PromptCacheMissDiagnosticsBody>(null, PromptCacheMissDiagnosticsBody);
            }
            else if(PromptCacheUnavailableDiagnosticsBody != null)
            {
                writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.PromptCacheUnavailableDiagnosticsBody>(null, PromptCacheUnavailableDiagnosticsBody);
            }
        }
    }
}
#pragma warning restore CS0618
