// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.OpenAI.OpenApiClient.Models
{
    /// <summary>
    /// Safe metadata for a first-class execution environment.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PublicEnvironmentResource : IParsable
    {
        /// <summary>Files installed in the environment, without their contents.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.OpenAI.OpenApiClient.Models.HostedEnvironmentFileResource>? Files { get; set; }
#nullable restore
#else
        public List<global::Soenneker.OpenAI.OpenApiClient.Models.HostedEnvironmentFileResource> Files { get; set; }
#endif
        /// <summary>The ID of the environment.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The object type. Always `agent.environment`.</summary>
        public global::Soenneker.OpenAI.OpenApiClient.Models.AgentEnvironmentObject? Object { get; set; }
        /// <summary>Plugins installed in the environment, without their archive contents.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.OpenAI.OpenApiClient.Models.HostedPluginResource>? Plugins { get; set; }
#nullable restore
#else
        public List<global::Soenneker.OpenAI.OpenApiClient.Models.HostedPluginResource> Plugins { get; set; }
#endif
        /// <summary>Skills installed in the environment, without their archive contents.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.OpenAI.OpenApiClient.Models.HostedSkillResource>? Skills { get; set; }
#nullable restore
#else
        public List<global::Soenneker.OpenAI.OpenApiClient.Models.HostedSkillResource> Skills { get; set; }
#endif
        /// <summary>The current environment connection status.</summary>
        public global::Soenneker.OpenAI.OpenApiClient.Models.EnvironmentStatusResource? Status { get; set; }
        /// <summary>Whether the environment is hosted by OpenAI or by the application.</summary>
        public global::Soenneker.OpenAI.OpenApiClient.Models.EnvironmentTypeResource? Type { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.PublicEnvironmentResource"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.OpenAI.OpenApiClient.Models.PublicEnvironmentResource CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.OpenAI.OpenApiClient.Models.PublicEnvironmentResource();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "files", n => { Files = n.GetCollectionOfObjectValues<global::Soenneker.OpenAI.OpenApiClient.Models.HostedEnvironmentFileResource>(global::Soenneker.OpenAI.OpenApiClient.Models.HostedEnvironmentFileResource.CreateFromDiscriminatorValue)?.AsList(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "object", n => { Object = n.GetEnumValue<global::Soenneker.OpenAI.OpenApiClient.Models.AgentEnvironmentObject>(); } },
                { "plugins", n => { Plugins = n.GetCollectionOfObjectValues<global::Soenneker.OpenAI.OpenApiClient.Models.HostedPluginResource>(global::Soenneker.OpenAI.OpenApiClient.Models.HostedPluginResource.CreateFromDiscriminatorValue)?.AsList(); } },
                { "skills", n => { Skills = n.GetCollectionOfObjectValues<global::Soenneker.OpenAI.OpenApiClient.Models.HostedSkillResource>(global::Soenneker.OpenAI.OpenApiClient.Models.HostedSkillResource.CreateFromDiscriminatorValue)?.AsList(); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.OpenAI.OpenApiClient.Models.EnvironmentStatusResource>(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.OpenAI.OpenApiClient.Models.EnvironmentTypeResource>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.OpenAI.OpenApiClient.Models.HostedEnvironmentFileResource>("files", Files);
            writer.WriteStringValue("id", Id);
            writer.WriteEnumValue<global::Soenneker.OpenAI.OpenApiClient.Models.AgentEnvironmentObject>("object", Object);
            writer.WriteCollectionOfObjectValues<global::Soenneker.OpenAI.OpenApiClient.Models.HostedPluginResource>("plugins", Plugins);
            writer.WriteCollectionOfObjectValues<global::Soenneker.OpenAI.OpenApiClient.Models.HostedSkillResource>("skills", Skills);
            writer.WriteEnumValue<global::Soenneker.OpenAI.OpenApiClient.Models.EnvironmentStatusResource>("status", Status);
            writer.WriteEnumValue<global::Soenneker.OpenAI.OpenApiClient.Models.EnvironmentTypeResource>("type", Type);
        }
    }
}
#pragma warning restore CS0618
