// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.OpenAI.OpenApiClient.Models
{
    /// <summary>
    /// A Realtime session configuration object.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RealtimeSessionCreateResponse : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Configuration for input and output audio for the session.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.RealtimeSessionCreateResponse_audio? Audio { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.RealtimeSessionCreateResponse_audio Audio { get; set; }
#endif
        /// <summary>Expiration timestamp for the session, in seconds since epoch.</summary>
        public int? ExpiresAt { get; set; }
        /// <summary>Unique identifier for the session that looks like `sess_1234567890abcdef`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Additional fields to include in server outputs.- `item.input_audio_transcription.logprobs`: Include logprobs for input audio transcription.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.OpenAI.OpenApiClient.Models.RealtimeSessionCreateResponse_include?>? Include { get; set; }
#nullable restore
#else
        public List<global::Soenneker.OpenAI.OpenApiClient.Models.RealtimeSessionCreateResponse_include?> Include { get; set; }
#endif
        /// <summary>The default system instructions (i.e. system message) prepended to modelcalls. This field allows the client to guide the model on desiredresponses. The model can be instructed on response content and format,(e.g. &quot;be extremely succinct&quot;, &quot;act friendly&quot;, &quot;here are examples of goodresponses&quot;) and on audio behavior (e.g. &quot;talk quickly&quot;, &quot;inject emotioninto your voice&quot;, &quot;laugh frequently&quot;). The instructions are not guaranteedto be followed by the model, but they provide guidance to the model on thedesired behavior.Note that the server sets default instructions which will be used if thisfield is not set and are visible in the `session.created` event at thestart of the session.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Instructions { get; set; }
#nullable restore
#else
        public string Instructions { get; set; }
#endif
        /// <summary>Maximum number of output tokens for a single assistant response,inclusive of tool calls. Provide an integer between 1 and 4096 tolimit output tokens, or `inf` for the maximum available tokens for agiven model. Defaults to `inf`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.RealtimeSessionCreateResponse.RealtimeSessionCreateResponse_max_output_tokens? MaxOutputTokens { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.RealtimeSessionCreateResponse.RealtimeSessionCreateResponse_max_output_tokens MaxOutputTokens { get; set; }
#endif
        /// <summary>The Realtime model used for this session.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Model { get; set; }
#nullable restore
#else
        public string Model { get; set; }
#endif
        /// <summary>The object type. Always `realtime.session`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Object { get; set; }
#nullable restore
#else
        public string Object { get; set; }
#endif
        /// <summary>The set of modalities the model can respond with. To disable audio,set this to [&quot;text&quot;].</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? OutputModalities { get; set; }
#nullable restore
#else
        public UntypedNode OutputModalities { get; set; }
#endif
        /// <summary>How the model chooses tools. Options are `auto`, `none`, `required`, orspecify a function.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ToolChoice { get; set; }
#nullable restore
#else
        public string ToolChoice { get; set; }
#endif
        /// <summary>Tools (functions) available to the model.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.OpenAI.OpenApiClient.Models.RealtimeFunctionTool>? Tools { get; set; }
#nullable restore
#else
        public List<global::Soenneker.OpenAI.OpenApiClient.Models.RealtimeFunctionTool> Tools { get; set; }
#endif
        /// <summary>Configuration options for tracing. Set to null to disable tracing. Oncetracing is enabled for a session, the configuration cannot be modified.`auto` will create a trace for the session with default values for theworkflow name, group id, and metadata.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.RealtimeSessionCreateResponse.RealtimeSessionCreateResponse_tracing? Tracing { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.RealtimeSessionCreateResponse.RealtimeSessionCreateResponse_tracing Tracing { get; set; }
#endif
        /// <summary>Configuration for turn detection. Can be set to `null` to turn off. ServerVAD means that the model will detect the start and end of speech based onaudio volume and respond at the end of user speech.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.RealtimeSessionCreateResponse_turn_detection? TurnDetection { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.RealtimeSessionCreateResponse_turn_detection TurnDetection { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.RealtimeSessionCreateResponse"/> and sets the default values.
        /// </summary>
        public RealtimeSessionCreateResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.RealtimeSessionCreateResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.OpenAI.OpenApiClient.Models.RealtimeSessionCreateResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.OpenAI.OpenApiClient.Models.RealtimeSessionCreateResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "audio", n => { Audio = n.GetObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.RealtimeSessionCreateResponse_audio>(global::Soenneker.OpenAI.OpenApiClient.Models.RealtimeSessionCreateResponse_audio.CreateFromDiscriminatorValue); } },
                { "expires_at", n => { ExpiresAt = n.GetIntValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "include", n => { Include = n.GetCollectionOfEnumValues<global::Soenneker.OpenAI.OpenApiClient.Models.RealtimeSessionCreateResponse_include>()?.AsList(); } },
                { "instructions", n => { Instructions = n.GetStringValue(); } },
                { "max_output_tokens", n => { MaxOutputTokens = n.GetObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.RealtimeSessionCreateResponse.RealtimeSessionCreateResponse_max_output_tokens>(global::Soenneker.OpenAI.OpenApiClient.Models.RealtimeSessionCreateResponse.RealtimeSessionCreateResponse_max_output_tokens.CreateFromDiscriminatorValue); } },
                { "model", n => { Model = n.GetStringValue(); } },
                { "object", n => { Object = n.GetStringValue(); } },
                { "output_modalities", n => { OutputModalities = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "tool_choice", n => { ToolChoice = n.GetStringValue(); } },
                { "tools", n => { Tools = n.GetCollectionOfObjectValues<global::Soenneker.OpenAI.OpenApiClient.Models.RealtimeFunctionTool>(global::Soenneker.OpenAI.OpenApiClient.Models.RealtimeFunctionTool.CreateFromDiscriminatorValue)?.AsList(); } },
                { "tracing", n => { Tracing = n.GetObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.RealtimeSessionCreateResponse.RealtimeSessionCreateResponse_tracing>(global::Soenneker.OpenAI.OpenApiClient.Models.RealtimeSessionCreateResponse.RealtimeSessionCreateResponse_tracing.CreateFromDiscriminatorValue); } },
                { "turn_detection", n => { TurnDetection = n.GetObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.RealtimeSessionCreateResponse_turn_detection>(global::Soenneker.OpenAI.OpenApiClient.Models.RealtimeSessionCreateResponse_turn_detection.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.RealtimeSessionCreateResponse_audio>("audio", Audio);
            writer.WriteIntValue("expires_at", ExpiresAt);
            writer.WriteStringValue("id", Id);
            writer.WriteCollectionOfEnumValues<global::Soenneker.OpenAI.OpenApiClient.Models.RealtimeSessionCreateResponse_include>("include", Include);
            writer.WriteStringValue("instructions", Instructions);
            writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.RealtimeSessionCreateResponse.RealtimeSessionCreateResponse_max_output_tokens>("max_output_tokens", MaxOutputTokens);
            writer.WriteStringValue("model", Model);
            writer.WriteStringValue("object", Object);
            writer.WriteObjectValue<UntypedNode>("output_modalities", OutputModalities);
            writer.WriteStringValue("tool_choice", ToolChoice);
            writer.WriteCollectionOfObjectValues<global::Soenneker.OpenAI.OpenApiClient.Models.RealtimeFunctionTool>("tools", Tools);
            writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.RealtimeSessionCreateResponse.RealtimeSessionCreateResponse_tracing>("tracing", Tracing);
            writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.RealtimeSessionCreateResponse_turn_detection>("turn_detection", TurnDetection);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="int"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class RealtimeSessionCreateResponse_max_output_tokens : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="int"/></summary>
            public int? Integer { get; set; }
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.RealtimeSessionCreateResponse.RealtimeSessionCreateResponse_max_output_tokens"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.OpenAI.OpenApiClient.Models.RealtimeSessionCreateResponse.RealtimeSessionCreateResponse_max_output_tokens CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::Soenneker.OpenAI.OpenApiClient.Models.RealtimeSessionCreateResponse.RealtimeSessionCreateResponse_max_output_tokens();
                if(parseNode.GetIntValue() is int integerValue)
                {
                    result.Integer = integerValue;
                }
                else if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(Integer != null)
                {
                    writer.WriteIntValue(null, Integer);
                }
                else if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.RealtimeSessionCreateResponse_tracingMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class RealtimeSessionCreateResponse_tracing : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.RealtimeSessionCreateResponse_tracingMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.OpenAI.OpenApiClient.Models.RealtimeSessionCreateResponse_tracingMember1? RealtimeSessionCreateResponseTracingMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.OpenAI.OpenApiClient.Models.RealtimeSessionCreateResponse_tracingMember1 RealtimeSessionCreateResponseTracingMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.RealtimeSessionCreateResponse.RealtimeSessionCreateResponse_tracing"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.OpenAI.OpenApiClient.Models.RealtimeSessionCreateResponse.RealtimeSessionCreateResponse_tracing CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::Soenneker.OpenAI.OpenApiClient.Models.RealtimeSessionCreateResponse.RealtimeSessionCreateResponse_tracing();
                if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.RealtimeSessionCreateResponseTracingMember1 = new global::Soenneker.OpenAI.OpenApiClient.Models.RealtimeSessionCreateResponse_tracingMember1();
                }
                else if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(RealtimeSessionCreateResponseTracingMember1 != null)
                {
                    return RealtimeSessionCreateResponseTracingMember1.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(RealtimeSessionCreateResponseTracingMember1 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.RealtimeSessionCreateResponse_tracingMember1>(null, RealtimeSessionCreateResponseTracingMember1);
                }
                else if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
            }
        }
    }
}
#pragma warning restore CS0618
