// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.OpenAI.OpenApiClient.Models
{
    /// <summary>The type of session to create. Always `realtime` for the Realtime API.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum RealtimeSessionCreateResponseGA_type
    {
        [EnumMember(Value = "realtime")]
        #pragma warning disable CS1591
        Realtime,
        #pragma warning restore CS1591
    }
}
