// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.OpenAI.OpenApiClient.Models
{
    /// <summary>Constrains effort on reasoning for reasoning-capable Realtime models such as`gpt-realtime-2`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum RealtimeReasoningEffort
    {
        [EnumMember(Value = "minimal")]
        #pragma warning disable CS1591
        Minimal,
        #pragma warning restore CS1591
        [EnumMember(Value = "low")]
        #pragma warning disable CS1591
        Low,
        #pragma warning restore CS1591
        [EnumMember(Value = "medium")]
        #pragma warning disable CS1591
        Medium,
        #pragma warning restore CS1591
        [EnumMember(Value = "high")]
        #pragma warning disable CS1591
        High,
        #pragma warning restore CS1591
        [EnumMember(Value = "xhigh")]
        #pragma warning disable CS1591
        Xhigh,
        #pragma warning restore CS1591
    }
}
