// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.OpenAI.OpenApiClient.Models
{
    /// <summary>The type of the event. Always `response.cancelled`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ResponseCancelledType
    {
        [EnumMember(Value = "response.cancelled")]
        #pragma warning disable CS1591
        ResponseCancelled,
        #pragma warning restore CS1591
    }
}
