// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.OpenAI.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ResponseValue : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The background property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.ResponsePropertiesBackground? Background { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.ResponsePropertiesBackground Background { get; set; }
#endif
        /// <summary>The completed_at property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.ResponseValueAllOf3CompletedAt? CompletedAt { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.ResponseValueAllOf3CompletedAt CompletedAt { get; set; }
#endif
        /// <summary>The conversation property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.ResponseValueAllOf3Conversation? Conversation { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.ResponseValueAllOf3Conversation Conversation { get; set; }
#endif
        /// <summary>Unix timestamp (in seconds) of when this Response was created.</summary>
        public double? CreatedAt { get; set; }
        /// <summary>The error property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.ResponseError? Error { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.ResponseError Error { get; set; }
#endif
        /// <summary>Unique identifier for this Response.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The incomplete_details property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.ResponseValueAllOf3IncompleteDetails? IncompleteDetails { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.ResponseValueAllOf3IncompleteDetails IncompleteDetails { get; set; }
#endif
        /// <summary>The instructions property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.ResponseValueAllOf3Instructions? Instructions { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.ResponseValueAllOf3Instructions Instructions { get; set; }
#endif
        /// <summary>The max_output_tokens property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.ResponseValueAllOf3MaxOutputTokens? MaxOutputTokens { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.ResponseValueAllOf3MaxOutputTokens MaxOutputTokens { get; set; }
#endif
        /// <summary>The max_tool_calls property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.ResponsePropertiesMaxToolCalls? MaxToolCalls { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.ResponsePropertiesMaxToolCalls MaxToolCalls { get; set; }
#endif
        /// <summary>The metadata property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.Metadata? Metadata { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.Metadata Metadata { get; set; }
#endif
        /// <summary>The model property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.ModelIdsResponses? Model { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.ModelIdsResponses Model { get; set; }
#endif
        /// <summary>The moderation property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.ResponseValueAllOf3Moderation? Moderation { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.ResponseValueAllOf3Moderation Moderation { get; set; }
#endif
        /// <summary>The object type of this resource - always set to `response`.</summary>
        public global::Soenneker.OpenAI.OpenApiClient.Models.ResponseValueObject? Object { get; set; }
        /// <summary>An array of content items generated by the model.- The length and order of items in the `output` array is dependent  on the model&apos;s response.- Rather than accessing the first item in the `output` array and  assuming it&apos;s an `assistant` message with the content generated by  the model, you might consider using the `output_text` property where  supported in SDKs.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.OpenAI.OpenApiClient.Models.OutputItem>? Output { get; set; }
#nullable restore
#else
        public List<global::Soenneker.OpenAI.OpenApiClient.Models.OutputItem> Output { get; set; }
#endif
        /// <summary>The output_text property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.ResponseValueAllOf3OutputText? OutputText { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.ResponseValueAllOf3OutputText OutputText { get; set; }
#endif
        /// <summary>Whether to allow the model to run tool calls in parallel.</summary>
        public bool? ParallelToolCalls { get; set; }
        /// <summary>The previous_response_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.ResponsePropertiesPreviousResponseId? PreviousResponseId { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.ResponsePropertiesPreviousResponseId PreviousResponseId { get; set; }
#endif
        /// <summary>The prompt property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.Prompt? Prompt { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.Prompt Prompt { get; set; }
#endif
        /// <summary>The prompt_cache_key property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.ModelResponsePropertiesPromptCacheKey? PromptCacheKey { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.ModelResponsePropertiesPromptCacheKey PromptCacheKey { get; set; }
#endif
        /// <summary>The prompt-caching options that were applied to the response. Supported for `gpt-5.6` and later models.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.PromptCacheOptions? PromptCacheOptions { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.PromptCacheOptions PromptCacheOptions { get; set; }
#endif
        /// <summary>The prompt_cache_retention property</summary>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.ModelResponsePropertiesPromptCacheRetention? PromptCacheRetention { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.ModelResponsePropertiesPromptCacheRetention PromptCacheRetention { get; set; }
#endif
        /// <summary>The reasoning property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.ResponseValueAllOf3Reasoning? Reasoning { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.ResponseValueAllOf3Reasoning Reasoning { get; set; }
#endif
        /// <summary>The safety_identifier property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.ModelResponsePropertiesSafetyIdentifier? SafetyIdentifier { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.ModelResponsePropertiesSafetyIdentifier SafetyIdentifier { get; set; }
#endif
        /// <summary>The service_tier property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.ServiceTier? ServiceTier { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.ServiceTier ServiceTier { get; set; }
#endif
        /// <summary>The status of the response generation. One of `completed`, `failed`,`in_progress`, `cancelled`, `queued`, or `incomplete`.</summary>
        public global::Soenneker.OpenAI.OpenApiClient.Models.ResponseValueStatus? Status { get; set; }
        /// <summary>The temperature property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.ModelResponsePropertiesTemperature? Temperature { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.ModelResponsePropertiesTemperature Temperature { get; set; }
#endif
        /// <summary>Configuration options for a text response from the model. Can be plaintext or structured JSON data. Learn more:- [Text inputs and outputs](/docs/guides/text)- [Structured Outputs](/docs/guides/structured-outputs)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.ResponseTextParam? Text { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.ResponseTextParam Text { get; set; }
#endif
        /// <summary>How the model should select which tool (or tools) to use when generatinga response. See the `tools` parameter to see how to specify which toolsthe model can call.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.ToolChoiceParam? ToolChoice { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.ToolChoiceParam ToolChoice { get; set; }
#endif
        /// <summary>&quot;An array of tools the model may call while generating a response. Youcan specify which tool to use by setting the `tool_choice` parameter.We support the following categories of tools:- **Built-in tools**: Tools that are provided by OpenAI that extend the  model&apos;s capabilities, like [web search](/docs/guides/tools-web-search)  or [file search](/docs/guides/tools-file-search). Learn more about  [built-in tools](/docs/guides/tools).- **MCP Tools**: Integrations with third-party systems via custom MCP servers  or predefined connectors such as Google Drive and SharePoint. Learn more about  [MCP Tools](/docs/guides/tools-connectors-mcp).- **Function calls (custom tools)**: Functions that are defined by you,  enabling the model to call your own code with strongly typed arguments  and outputs. Learn more about  [function calling](/docs/guides/function-calling). You can also use  custom tools to call your own code.&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.OpenAI.OpenApiClient.Models.Tool>? Tools { get; set; }
#nullable restore
#else
        public List<global::Soenneker.OpenAI.OpenApiClient.Models.Tool> Tools { get; set; }
#endif
        /// <summary>The top_logprobs property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.ModelResponsePropertiesTopLogprobs? TopLogprobs { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.ModelResponsePropertiesTopLogprobs TopLogprobs { get; set; }
#endif
        /// <summary>The top_p property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.ModelResponsePropertiesTopP? TopP { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.ModelResponsePropertiesTopP TopP { get; set; }
#endif
        /// <summary>The truncation property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.ResponseValueAllOf3Truncation? Truncation { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.ResponseValueAllOf3Truncation Truncation { get; set; }
#endif
        /// <summary>Represents token usage details including input tokens, output tokens,a breakdown of output tokens, and the total tokens used.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.ResponseUsage? Usage { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.ResponseUsage Usage { get; set; }
#endif
        /// <summary>This field is being replaced by `safety_identifier` and `prompt_cache_key`. Use `prompt_cache_key` instead to maintain caching optimizations.A stable identifier for your end-users.Used to boost cache hit rates by better bucketing similar requests and  to help OpenAI detect and prevent abuse. [Learn more](/docs/guides/safety-best-practices#safety-identifiers).</summary>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? User { get; set; }
#nullable restore
#else
        public string User { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.ResponseValue"/> and sets the default values.
        /// </summary>
        public ResponseValue()
        {
            AdditionalData = new Dictionary<string, object>();
            ParallelToolCalls = true;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.ResponseValue"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.OpenAI.OpenApiClient.Models.ResponseValue CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.OpenAI.OpenApiClient.Models.ResponseValue();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "background", n => { Background = n.GetObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.ResponsePropertiesBackground>(global::Soenneker.OpenAI.OpenApiClient.Models.ResponsePropertiesBackground.CreateFromDiscriminatorValue); } },
                { "completed_at", n => { CompletedAt = n.GetObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.ResponseValueAllOf3CompletedAt>(global::Soenneker.OpenAI.OpenApiClient.Models.ResponseValueAllOf3CompletedAt.CreateFromDiscriminatorValue); } },
                { "conversation", n => { Conversation = n.GetObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.ResponseValueAllOf3Conversation>(global::Soenneker.OpenAI.OpenApiClient.Models.ResponseValueAllOf3Conversation.CreateFromDiscriminatorValue); } },
                { "created_at", n => { CreatedAt = n.GetDoubleValue(); } },
                { "error", n => { Error = n.GetObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.ResponseError>(global::Soenneker.OpenAI.OpenApiClient.Models.ResponseError.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "incomplete_details", n => { IncompleteDetails = n.GetObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.ResponseValueAllOf3IncompleteDetails>(global::Soenneker.OpenAI.OpenApiClient.Models.ResponseValueAllOf3IncompleteDetails.CreateFromDiscriminatorValue); } },
                { "instructions", n => { Instructions = n.GetObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.ResponseValueAllOf3Instructions>(global::Soenneker.OpenAI.OpenApiClient.Models.ResponseValueAllOf3Instructions.CreateFromDiscriminatorValue); } },
                { "max_output_tokens", n => { MaxOutputTokens = n.GetObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.ResponseValueAllOf3MaxOutputTokens>(global::Soenneker.OpenAI.OpenApiClient.Models.ResponseValueAllOf3MaxOutputTokens.CreateFromDiscriminatorValue); } },
                { "max_tool_calls", n => { MaxToolCalls = n.GetObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.ResponsePropertiesMaxToolCalls>(global::Soenneker.OpenAI.OpenApiClient.Models.ResponsePropertiesMaxToolCalls.CreateFromDiscriminatorValue); } },
                { "metadata", n => { Metadata = n.GetObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.Metadata>(global::Soenneker.OpenAI.OpenApiClient.Models.Metadata.CreateFromDiscriminatorValue); } },
                { "model", n => { Model = n.GetObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.ModelIdsResponses>(global::Soenneker.OpenAI.OpenApiClient.Models.ModelIdsResponses.CreateFromDiscriminatorValue); } },
                { "moderation", n => { Moderation = n.GetObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.ResponseValueAllOf3Moderation>(global::Soenneker.OpenAI.OpenApiClient.Models.ResponseValueAllOf3Moderation.CreateFromDiscriminatorValue); } },
                { "object", n => { Object = n.GetEnumValue<global::Soenneker.OpenAI.OpenApiClient.Models.ResponseValueObject>(); } },
                { "output", n => { Output = n.GetCollectionOfObjectValues<global::Soenneker.OpenAI.OpenApiClient.Models.OutputItem>(global::Soenneker.OpenAI.OpenApiClient.Models.OutputItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "output_text", n => { OutputText = n.GetObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.ResponseValueAllOf3OutputText>(global::Soenneker.OpenAI.OpenApiClient.Models.ResponseValueAllOf3OutputText.CreateFromDiscriminatorValue); } },
                { "parallel_tool_calls", n => { ParallelToolCalls = n.GetBoolValue(); } },
                { "previous_response_id", n => { PreviousResponseId = n.GetObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.ResponsePropertiesPreviousResponseId>(global::Soenneker.OpenAI.OpenApiClient.Models.ResponsePropertiesPreviousResponseId.CreateFromDiscriminatorValue); } },
                { "prompt", n => { Prompt = n.GetObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.Prompt>(global::Soenneker.OpenAI.OpenApiClient.Models.Prompt.CreateFromDiscriminatorValue); } },
                { "prompt_cache_key", n => { PromptCacheKey = n.GetObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.ModelResponsePropertiesPromptCacheKey>(global::Soenneker.OpenAI.OpenApiClient.Models.ModelResponsePropertiesPromptCacheKey.CreateFromDiscriminatorValue); } },
                { "prompt_cache_options", n => { PromptCacheOptions = n.GetObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.PromptCacheOptions>(global::Soenneker.OpenAI.OpenApiClient.Models.PromptCacheOptions.CreateFromDiscriminatorValue); } },
                { "prompt_cache_retention", n => { PromptCacheRetention = n.GetObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.ModelResponsePropertiesPromptCacheRetention>(global::Soenneker.OpenAI.OpenApiClient.Models.ModelResponsePropertiesPromptCacheRetention.CreateFromDiscriminatorValue); } },
                { "reasoning", n => { Reasoning = n.GetObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.ResponseValueAllOf3Reasoning>(global::Soenneker.OpenAI.OpenApiClient.Models.ResponseValueAllOf3Reasoning.CreateFromDiscriminatorValue); } },
                { "safety_identifier", n => { SafetyIdentifier = n.GetObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.ModelResponsePropertiesSafetyIdentifier>(global::Soenneker.OpenAI.OpenApiClient.Models.ModelResponsePropertiesSafetyIdentifier.CreateFromDiscriminatorValue); } },
                { "service_tier", n => { ServiceTier = n.GetObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.ServiceTier>(global::Soenneker.OpenAI.OpenApiClient.Models.ServiceTier.CreateFromDiscriminatorValue); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.OpenAI.OpenApiClient.Models.ResponseValueStatus>(); } },
                { "temperature", n => { Temperature = n.GetObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.ModelResponsePropertiesTemperature>(global::Soenneker.OpenAI.OpenApiClient.Models.ModelResponsePropertiesTemperature.CreateFromDiscriminatorValue); } },
                { "text", n => { Text = n.GetObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.ResponseTextParam>(global::Soenneker.OpenAI.OpenApiClient.Models.ResponseTextParam.CreateFromDiscriminatorValue); } },
                { "tool_choice", n => { ToolChoice = n.GetObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.ToolChoiceParam>(global::Soenneker.OpenAI.OpenApiClient.Models.ToolChoiceParam.CreateFromDiscriminatorValue); } },
                { "tools", n => { Tools = n.GetCollectionOfObjectValues<global::Soenneker.OpenAI.OpenApiClient.Models.Tool>(global::Soenneker.OpenAI.OpenApiClient.Models.Tool.CreateFromDiscriminatorValue)?.AsList(); } },
                { "top_logprobs", n => { TopLogprobs = n.GetObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.ModelResponsePropertiesTopLogprobs>(global::Soenneker.OpenAI.OpenApiClient.Models.ModelResponsePropertiesTopLogprobs.CreateFromDiscriminatorValue); } },
                { "top_p", n => { TopP = n.GetObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.ModelResponsePropertiesTopP>(global::Soenneker.OpenAI.OpenApiClient.Models.ModelResponsePropertiesTopP.CreateFromDiscriminatorValue); } },
                { "truncation", n => { Truncation = n.GetObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.ResponseValueAllOf3Truncation>(global::Soenneker.OpenAI.OpenApiClient.Models.ResponseValueAllOf3Truncation.CreateFromDiscriminatorValue); } },
                { "usage", n => { Usage = n.GetObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.ResponseUsage>(global::Soenneker.OpenAI.OpenApiClient.Models.ResponseUsage.CreateFromDiscriminatorValue); } },
                { "user", n => { User = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.ResponsePropertiesBackground>("background", Background);
            writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.ResponseValueAllOf3CompletedAt>("completed_at", CompletedAt);
            writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.ResponseValueAllOf3Conversation>("conversation", Conversation);
            writer.WriteDoubleValue("created_at", CreatedAt);
            writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.ResponseError>("error", Error);
            writer.WriteStringValue("id", Id);
            writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.ResponseValueAllOf3IncompleteDetails>("incomplete_details", IncompleteDetails);
            writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.ResponseValueAllOf3Instructions>("instructions", Instructions);
            writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.ResponseValueAllOf3MaxOutputTokens>("max_output_tokens", MaxOutputTokens);
            writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.ResponsePropertiesMaxToolCalls>("max_tool_calls", MaxToolCalls);
            writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.Metadata>("metadata", Metadata);
            writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.ModelIdsResponses>("model", Model);
            writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.ResponseValueAllOf3Moderation>("moderation", Moderation);
            writer.WriteEnumValue<global::Soenneker.OpenAI.OpenApiClient.Models.ResponseValueObject>("object", Object);
            writer.WriteCollectionOfObjectValues<global::Soenneker.OpenAI.OpenApiClient.Models.OutputItem>("output", Output);
            writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.ResponseValueAllOf3OutputText>("output_text", OutputText);
            writer.WriteBoolValue("parallel_tool_calls", ParallelToolCalls);
            writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.ResponsePropertiesPreviousResponseId>("previous_response_id", PreviousResponseId);
            writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.Prompt>("prompt", Prompt);
            writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.ModelResponsePropertiesPromptCacheKey>("prompt_cache_key", PromptCacheKey);
            writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.PromptCacheOptions>("prompt_cache_options", PromptCacheOptions);
            writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.ModelResponsePropertiesPromptCacheRetention>("prompt_cache_retention", PromptCacheRetention);
            writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.ResponseValueAllOf3Reasoning>("reasoning", Reasoning);
            writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.ModelResponsePropertiesSafetyIdentifier>("safety_identifier", SafetyIdentifier);
            writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.ServiceTier>("service_tier", ServiceTier);
            writer.WriteEnumValue<global::Soenneker.OpenAI.OpenApiClient.Models.ResponseValueStatus>("status", Status);
            writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.ModelResponsePropertiesTemperature>("temperature", Temperature);
            writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.ResponseTextParam>("text", Text);
            writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.ToolChoiceParam>("tool_choice", ToolChoice);
            writer.WriteCollectionOfObjectValues<global::Soenneker.OpenAI.OpenApiClient.Models.Tool>("tools", Tools);
            writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.ModelResponsePropertiesTopLogprobs>("top_logprobs", TopLogprobs);
            writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.ModelResponsePropertiesTopP>("top_p", TopP);
            writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.ResponseValueAllOf3Truncation>("truncation", Truncation);
            writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.ResponseUsage>("usage", Usage);
            writer.WriteStringValue("user", User);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
