// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.OpenAI.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.RunStepDetailsMessageCreationObject"/>, <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.RunStepDetailsToolCallsObject"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RunStepObjectStepDetails : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.RunStepDetailsMessageCreationObject"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.RunStepDetailsMessageCreationObject? RunStepDetailsMessageCreationObject { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.RunStepDetailsMessageCreationObject RunStepDetailsMessageCreationObject { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.RunStepDetailsToolCallsObject"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.RunStepDetailsToolCallsObject? RunStepDetailsToolCallsObject { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.RunStepDetailsToolCallsObject RunStepDetailsToolCallsObject { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.RunStepObjectStepDetails"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.OpenAI.OpenApiClient.Models.RunStepObjectStepDetails CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            var result = new global::Soenneker.OpenAI.OpenApiClient.Models.RunStepObjectStepDetails();
            if("RunStepDetailsMessageCreationObject".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.RunStepDetailsMessageCreationObject = new global::Soenneker.OpenAI.OpenApiClient.Models.RunStepDetailsMessageCreationObject();
            }
            else if("RunStepDetailsToolCallsObject".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.RunStepDetailsToolCallsObject = new global::Soenneker.OpenAI.OpenApiClient.Models.RunStepDetailsToolCallsObject();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(RunStepDetailsMessageCreationObject != null)
            {
                return RunStepDetailsMessageCreationObject.GetFieldDeserializers();
            }
            else if(RunStepDetailsToolCallsObject != null)
            {
                return RunStepDetailsToolCallsObject.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(RunStepDetailsMessageCreationObject != null)
            {
                writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.RunStepDetailsMessageCreationObject>(null, RunStepDetailsMessageCreationObject);
            }
            else if(RunStepDetailsToolCallsObject != null)
            {
                writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.RunStepDetailsToolCallsObject>(null, RunStepDetailsToolCallsObject);
            }
        }
    }
}
#pragma warning restore CS0618
