// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.OpenAI.OpenApiClient.Models
{
    /// <summary>The service tier to use for this request.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ServiceTierEnum
    {
        [EnumMember(Value = "auto")]
        #pragma warning disable CS1591
        Auto,
        #pragma warning restore CS1591
        [EnumMember(Value = "default")]
        #pragma warning disable CS1591
        Default,
        #pragma warning restore CS1591
        [EnumMember(Value = "flex")]
        #pragma warning disable CS1591
        Flex,
        #pragma warning restore CS1591
        [EnumMember(Value = "priority")]
        #pragma warning disable CS1591
        Priority,
        #pragma warning restore CS1591
    }
}
