// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.OpenAI.OpenApiClient.Models
{
    /// <summary>Type discriminator that is always `chatkit.task_group`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum TaskGroupItem_type
    {
        [EnumMember(Value = "chatkit.task_group")]
        #pragma warning disable CS1591
        ChatkitTask_group,
        #pragma warning restore CS1591
    }
}
