// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.OpenAI.OpenApiClient.Models
{
    /// <summary>
    /// How the model should select which tool (or tools) to use when generatinga response. See the `tools` parameter to see how to specify which toolsthe model can call.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ToolChoiceParam : IAdditionalDataHolder, IComposedTypeWrapper, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Constrains the tools available to the model to a pre-defined set.`auto` allows the model to pick from among the allowed tools and generate amessage.`required` requires the model to call one or more of the allowed tools.</summary>
        public global::Soenneker.OpenAI.OpenApiClient.Models.ToolChoiceAllowedMode? Mode { get; set; }
        /// <summary>The name of the function to call.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The label of the MCP server to use.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ServerLabel { get; set; }
#nullable restore
#else
        public string ServerLabel { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.SpecificApplyPatchParam"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.SpecificApplyPatchParam? SpecificApplyPatchParam { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.SpecificApplyPatchParam SpecificApplyPatchParam { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.SpecificFunctionShellParam"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.SpecificFunctionShellParam? SpecificFunctionShellParam { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.SpecificFunctionShellParam SpecificFunctionShellParam { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.SpecificProgrammaticToolCallingParam"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.SpecificProgrammaticToolCallingParam? SpecificProgrammaticToolCallingParam { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.SpecificProgrammaticToolCallingParam SpecificProgrammaticToolCallingParam { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.ToolChoiceAllowed"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.ToolChoiceAllowed? ToolChoiceAllowed { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.ToolChoiceAllowed ToolChoiceAllowed { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.ToolChoiceCustom"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.ToolChoiceCustom? ToolChoiceCustom { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.ToolChoiceCustom ToolChoiceCustom { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.ToolChoiceFunction"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.ToolChoiceFunction? ToolChoiceFunction { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.ToolChoiceFunction ToolChoiceFunction { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.ToolChoiceMcp"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.ToolChoiceMcp? ToolChoiceMcp { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.ToolChoiceMcp ToolChoiceMcp { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.ToolChoiceOptionsWrapper"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.ToolChoiceOptionsWrapper? ToolChoiceOptionsWrapper { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.ToolChoiceOptionsWrapper ToolChoiceOptionsWrapper { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.ToolChoiceTypes"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenAI.OpenApiClient.Models.ToolChoiceTypes? ToolChoiceTypes { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenAI.OpenApiClient.Models.ToolChoiceTypes ToolChoiceTypes { get; set; }
#endif
        /// <summary>A list of tool definitions that the model should be allowed to call.For the Responses API, the list of tool definitions might look like:```json[  { &quot;type&quot;: &quot;function&quot;, &quot;name&quot;: &quot;get_weather&quot; },  { &quot;type&quot;: &quot;mcp&quot;, &quot;server_label&quot;: &quot;deepwiki&quot; },  { &quot;type&quot;: &quot;image_generation&quot; }]```</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.OpenAI.OpenApiClient.Models.ToolChoiceAllowedToolsItemProperty>? Tools { get; set; }
#nullable restore
#else
        public List<global::Soenneker.OpenAI.OpenApiClient.Models.ToolChoiceAllowedToolsItemProperty> Tools { get; set; }
#endif
        /// <summary>Allowed tool configuration type. Always `allowed_tools`.</summary>
        public global::Soenneker.OpenAI.OpenApiClient.Models.AllowedToolsType? Type { get; set; }
        /// <summary>Controls which (if any) tool is called by the model.`none` means the model will not call any tool and instead generates a message.`auto` means the model can pick between generating a message or calling one ormore tools.`required` means the model must call one or more tools.</summary>
        public global::Soenneker.OpenAI.OpenApiClient.Models.ToolChoiceOptions? Value { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.ToolChoiceParam"/> and sets the default values.
        /// </summary>
        public ToolChoiceParam()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.ToolChoiceParam"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.OpenAI.OpenApiClient.Models.ToolChoiceParam CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
            var result = new global::Soenneker.OpenAI.OpenApiClient.Models.ToolChoiceParam();
            if(parseNode.GetEnumValue<global::Soenneker.OpenAI.OpenApiClient.Models.ToolChoiceAllowedMode>() is global::Soenneker.OpenAI.OpenApiClient.Models.ToolChoiceAllowedMode modeValue)
            {
                result.Mode = modeValue;
            }
            else if("SpecificApplyPatchParam".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.SpecificApplyPatchParam = new global::Soenneker.OpenAI.OpenApiClient.Models.SpecificApplyPatchParam();
            }
            else if("SpecificFunctionShellParam".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.SpecificFunctionShellParam = new global::Soenneker.OpenAI.OpenApiClient.Models.SpecificFunctionShellParam();
            }
            else if("SpecificProgrammaticToolCallingParam".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.SpecificProgrammaticToolCallingParam = new global::Soenneker.OpenAI.OpenApiClient.Models.SpecificProgrammaticToolCallingParam();
            }
            else if("ToolChoiceAllowed".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ToolChoiceAllowed = new global::Soenneker.OpenAI.OpenApiClient.Models.ToolChoiceAllowed();
            }
            else if("ToolChoiceCustom".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ToolChoiceCustom = new global::Soenneker.OpenAI.OpenApiClient.Models.ToolChoiceCustom();
            }
            else if("ToolChoiceFunction".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ToolChoiceFunction = new global::Soenneker.OpenAI.OpenApiClient.Models.ToolChoiceFunction();
            }
            else if("ToolChoiceMcp".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ToolChoiceMcp = new global::Soenneker.OpenAI.OpenApiClient.Models.ToolChoiceMcp();
            }
            else if("ToolChoiceOptionsWrapper".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ToolChoiceOptionsWrapper = new global::Soenneker.OpenAI.OpenApiClient.Models.ToolChoiceOptionsWrapper();
            }
            else if("ToolChoiceTypes".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ToolChoiceTypes = new global::Soenneker.OpenAI.OpenApiClient.Models.ToolChoiceTypes();
            }
            else if(parseNode.GetEnumValue<global::Soenneker.OpenAI.OpenApiClient.Models.AllowedToolsType>() is global::Soenneker.OpenAI.OpenApiClient.Models.AllowedToolsType typeValue)
            {
                result.Type = typeValue;
            }
            else if(parseNode.GetEnumValue<global::Soenneker.OpenAI.OpenApiClient.Models.ToolChoiceOptions>() is global::Soenneker.OpenAI.OpenApiClient.Models.ToolChoiceOptions valueValue)
            {
                result.Value = valueValue;
            }
            else if(parseNode.GetStringValue() is string nameValue)
            {
                result.Name = nameValue;
            }
            else if(parseNode.GetStringValue() is string serverLabelValue)
            {
                result.ServerLabel = serverLabelValue;
            }
            else if(parseNode.GetCollectionOfObjectValues<global::Soenneker.OpenAI.OpenApiClient.Models.ToolChoiceAllowedToolsItemProperty>(global::Soenneker.OpenAI.OpenApiClient.Models.ToolChoiceAllowedToolsItemProperty.CreateFromDiscriminatorValue)?.AsList() is List<global::Soenneker.OpenAI.OpenApiClient.Models.ToolChoiceAllowedToolsItemProperty> toolsValue)
            {
                result.Tools = toolsValue;
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(SpecificApplyPatchParam != null)
            {
                return SpecificApplyPatchParam.GetFieldDeserializers();
            }
            else if(SpecificFunctionShellParam != null)
            {
                return SpecificFunctionShellParam.GetFieldDeserializers();
            }
            else if(SpecificProgrammaticToolCallingParam != null)
            {
                return SpecificProgrammaticToolCallingParam.GetFieldDeserializers();
            }
            else if(ToolChoiceAllowed != null)
            {
                return ToolChoiceAllowed.GetFieldDeserializers();
            }
            else if(ToolChoiceCustom != null)
            {
                return ToolChoiceCustom.GetFieldDeserializers();
            }
            else if(ToolChoiceFunction != null)
            {
                return ToolChoiceFunction.GetFieldDeserializers();
            }
            else if(ToolChoiceMcp != null)
            {
                return ToolChoiceMcp.GetFieldDeserializers();
            }
            else if(ToolChoiceOptionsWrapper != null)
            {
                return ToolChoiceOptionsWrapper.GetFieldDeserializers();
            }
            else if(ToolChoiceTypes != null)
            {
                return ToolChoiceTypes.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(Mode != null)
            {
                writer.WriteEnumValue<global::Soenneker.OpenAI.OpenApiClient.Models.ToolChoiceAllowedMode>(null, Mode);
            }
            else if(SpecificApplyPatchParam != null)
            {
                writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.SpecificApplyPatchParam>(null, SpecificApplyPatchParam);
            }
            else if(SpecificFunctionShellParam != null)
            {
                writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.SpecificFunctionShellParam>(null, SpecificFunctionShellParam);
            }
            else if(SpecificProgrammaticToolCallingParam != null)
            {
                writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.SpecificProgrammaticToolCallingParam>(null, SpecificProgrammaticToolCallingParam);
            }
            else if(ToolChoiceAllowed != null)
            {
                writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.ToolChoiceAllowed>(null, ToolChoiceAllowed);
            }
            else if(ToolChoiceCustom != null)
            {
                writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.ToolChoiceCustom>(null, ToolChoiceCustom);
            }
            else if(ToolChoiceFunction != null)
            {
                writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.ToolChoiceFunction>(null, ToolChoiceFunction);
            }
            else if(ToolChoiceMcp != null)
            {
                writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.ToolChoiceMcp>(null, ToolChoiceMcp);
            }
            else if(ToolChoiceOptionsWrapper != null)
            {
                writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.ToolChoiceOptionsWrapper>(null, ToolChoiceOptionsWrapper);
            }
            else if(ToolChoiceTypes != null)
            {
                writer.WriteObjectValue<global::Soenneker.OpenAI.OpenApiClient.Models.ToolChoiceTypes>(null, ToolChoiceTypes);
            }
            else if(Type != null)
            {
                writer.WriteEnumValue<global::Soenneker.OpenAI.OpenApiClient.Models.AllowedToolsType>(null, Type);
            }
            else if(Value != null)
            {
                writer.WriteEnumValue<global::Soenneker.OpenAI.OpenApiClient.Models.ToolChoiceOptions>(null, Value);
            }
            else if(Name != null)
            {
                writer.WriteStringValue(null, Name);
            }
            else if(ServerLabel != null)
            {
                writer.WriteStringValue(null, ServerLabel);
            }
            else if(Tools != null)
            {
                writer.WriteCollectionOfObjectValues<global::Soenneker.OpenAI.OpenApiClient.Models.ToolChoiceAllowedToolsItemProperty>(null, Tools);
            }
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
