// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.OpenAI.OpenApiClient.Models
{
    /// <summary>The type of hosted tool the model should to use. Learn more about[built-in tools](/docs/guides/tools).Allowed values are:- `file_search`- `web_search_preview`- `computer`- `computer_use_preview`- `computer_use`- `code_interpreter`- `image_generation`</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ToolChoiceTypes_type
    {
        [EnumMember(Value = "file_search")]
        #pragma warning disable CS1591
        File_search,
        #pragma warning restore CS1591
        [EnumMember(Value = "web_search_preview")]
        #pragma warning disable CS1591
        Web_search_preview,
        #pragma warning restore CS1591
        [EnumMember(Value = "computer")]
        #pragma warning disable CS1591
        Computer,
        #pragma warning restore CS1591
        [EnumMember(Value = "computer_use_preview")]
        #pragma warning disable CS1591
        Computer_use_preview,
        #pragma warning restore CS1591
        [EnumMember(Value = "computer_use")]
        #pragma warning disable CS1591
        Computer_use,
        #pragma warning restore CS1591
        [EnumMember(Value = "web_search_preview_2025_03_11")]
        #pragma warning disable CS1591
        Web_search_preview_2025_03_11,
        #pragma warning restore CS1591
        [EnumMember(Value = "image_generation")]
        #pragma warning disable CS1591
        Image_generation,
        #pragma warning restore CS1591
        [EnumMember(Value = "code_interpreter")]
        #pragma warning disable CS1591
        Code_interpreter,
        #pragma warning restore CS1591
    }
}
