// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.OpenAI.OpenApiClient.Models
{
    /// <summary>
    /// A segment of diarized transcript text with speaker metadata.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TranscriptionDiarizedSegment : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>End timestamp of the segment in seconds.</summary>
        public float? End { get; set; }
        /// <summary>Unique identifier for the segment.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Speaker label for this segment. When known speakers are provided, the label matches `known_speaker_names[]`. Otherwise speakers are labeled sequentially using capital letters (`A`, `B`, ...).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Speaker { get; set; }
#nullable restore
#else
        public string Speaker { get; set; }
#endif
        /// <summary>Start timestamp of the segment in seconds.</summary>
        public float? Start { get; set; }
        /// <summary>Transcript text for this segment.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Text { get; set; }
#nullable restore
#else
        public string Text { get; set; }
#endif
        /// <summary>The type of the segment. Always `transcript.text.segment`.</summary>
        public global::Soenneker.OpenAI.OpenApiClient.Models.TranscriptionDiarizedSegment_type? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.TranscriptionDiarizedSegment"/> and sets the default values.
        /// </summary>
        public TranscriptionDiarizedSegment()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.TranscriptionDiarizedSegment"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.OpenAI.OpenApiClient.Models.TranscriptionDiarizedSegment CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.OpenAI.OpenApiClient.Models.TranscriptionDiarizedSegment();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "end", n => { End = n.GetFloatValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "speaker", n => { Speaker = n.GetStringValue(); } },
                { "start", n => { Start = n.GetFloatValue(); } },
                { "text", n => { Text = n.GetStringValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.OpenAI.OpenApiClient.Models.TranscriptionDiarizedSegment_type>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteFloatValue("end", End);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("speaker", Speaker);
            writer.WriteFloatValue("start", Start);
            writer.WriteStringValue("text", Text);
            writer.WriteEnumValue<global::Soenneker.OpenAI.OpenApiClient.Models.TranscriptionDiarizedSegment_type>("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
