// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.OpenAI.OpenApiClient.Models
{
    /// <summary>
    /// The aggregated web search calls usage details of the specific time bucket.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UsageWebSearchCallsResult : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>When `group_by=api_key_id`, this field provides the API key ID of the grouped usage result.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ApiKeyId { get; set; }
#nullable restore
#else
        public string ApiKeyId { get; set; }
#endif
        /// <summary>When `group_by=context_level`, this field provides the search context size of the grouped usage result.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ContextLevel { get; set; }
#nullable restore
#else
        public string ContextLevel { get; set; }
#endif
        /// <summary>When `group_by=model`, this field provides the model name of the grouped usage result.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Model { get; set; }
#nullable restore
#else
        public string Model { get; set; }
#endif
        /// <summary>The count of model requests.</summary>
        public int? NumModelRequests { get; set; }
        /// <summary>The count of web search calls.</summary>
        public int? NumRequests { get; set; }
        /// <summary>The object property</summary>
        public global::Soenneker.OpenAI.OpenApiClient.Models.UsageWebSearchCallsResultObject? Object { get; set; }
        /// <summary>When `group_by=project_id`, this field provides the project ID of the grouped usage result.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProjectId { get; set; }
#nullable restore
#else
        public string ProjectId { get; set; }
#endif
        /// <summary>When `group_by=user_id`, this field provides the user ID of the grouped usage result.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserId { get; set; }
#nullable restore
#else
        public string UserId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.UsageWebSearchCallsResult"/> and sets the default values.
        /// </summary>
        public UsageWebSearchCallsResult()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.UsageWebSearchCallsResult"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.OpenAI.OpenApiClient.Models.UsageWebSearchCallsResult CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.OpenAI.OpenApiClient.Models.UsageWebSearchCallsResult();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "api_key_id", n => { ApiKeyId = n.GetStringValue(); } },
                { "context_level", n => { ContextLevel = n.GetStringValue(); } },
                { "model", n => { Model = n.GetStringValue(); } },
                { "num_model_requests", n => { NumModelRequests = n.GetIntValue(); } },
                { "num_requests", n => { NumRequests = n.GetIntValue(); } },
                { "object", n => { Object = n.GetEnumValue<global::Soenneker.OpenAI.OpenApiClient.Models.UsageWebSearchCallsResultObject>(); } },
                { "project_id", n => { ProjectId = n.GetStringValue(); } },
                { "user_id", n => { UserId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("api_key_id", ApiKeyId);
            writer.WriteStringValue("context_level", ContextLevel);
            writer.WriteStringValue("model", Model);
            writer.WriteIntValue("num_model_requests", NumModelRequests);
            writer.WriteIntValue("num_requests", NumRequests);
            writer.WriteEnumValue<global::Soenneker.OpenAI.OpenApiClient.Models.UsageWebSearchCallsResultObject>("object", Object);
            writer.WriteStringValue("project_id", ProjectId);
            writer.WriteStringValue("user_id", UserId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
