// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.OpenAI.OpenApiClient.Models
{
    /// <summary>The object type. Always `vault.credential`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum VaultCredentialObject
    {
        [EnumMember(Value = "vault.credential")]
        #pragma warning disable CS1591
        VaultCredential,
        #pragma warning restore CS1591
    }
}
