// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.OpenAI.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum VoiceIdsShared_Wrapper_value
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "alloy")]
        #pragma warning disable CS1591
        Alloy,
        #pragma warning restore CS1591
        [EnumMember(Value = "ash")]
        #pragma warning disable CS1591
        Ash,
        #pragma warning restore CS1591
        [EnumMember(Value = "ballad")]
        #pragma warning disable CS1591
        Ballad,
        #pragma warning restore CS1591
        [EnumMember(Value = "coral")]
        #pragma warning disable CS1591
        Coral,
        #pragma warning restore CS1591
        [EnumMember(Value = "echo")]
        #pragma warning disable CS1591
        Echo,
        #pragma warning restore CS1591
        [EnumMember(Value = "sage")]
        #pragma warning disable CS1591
        Sage,
        #pragma warning restore CS1591
        [EnumMember(Value = "shimmer")]
        #pragma warning disable CS1591
        Shimmer,
        #pragma warning restore CS1591
        [EnumMember(Value = "verse")]
        #pragma warning disable CS1591
        Verse,
        #pragma warning restore CS1591
        [EnumMember(Value = "marin")]
        #pragma warning disable CS1591
        Marin,
        #pragma warning restore CS1591
        [EnumMember(Value = "cedar")]
        #pragma warning disable CS1591
        Cedar,
        #pragma warning restore CS1591
    }
}
