// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.OpenAI.OpenApiClient.Models;
using Soenneker.OpenAI.OpenApiClient.Organization.Projects.Item.Certificates.Activate;
using Soenneker.OpenAI.OpenApiClient.Organization.Projects.Item.Certificates.Deactivate;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.OpenAI.OpenApiClient.Organization.Projects.Item.Certificates
{
    /// <summary>
    /// Builds and executes requests for operations under \organization\projects\{project_id}\certificates
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CertificatesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The activate property</summary>
        public global::Soenneker.OpenAI.OpenApiClient.Organization.Projects.Item.Certificates.Activate.ActivateRequestBuilder Activate
        {
            get => new global::Soenneker.OpenAI.OpenApiClient.Organization.Projects.Item.Certificates.Activate.ActivateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The deactivate property</summary>
        public global::Soenneker.OpenAI.OpenApiClient.Organization.Projects.Item.Certificates.Deactivate.DeactivateRequestBuilder Deactivate
        {
            get => new global::Soenneker.OpenAI.OpenApiClient.Organization.Projects.Item.Certificates.Deactivate.DeactivateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenAI.OpenApiClient.Organization.Projects.Item.Certificates.CertificatesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CertificatesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/organization/projects/{project_id}/certificates{?after*,limit*,order*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenAI.OpenApiClient.Organization.Projects.Item.Certificates.CertificatesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CertificatesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/organization/projects/{project_id}/certificates{?after*,limit*,order*}", rawUrl)
        {
        }
        /// <summary>
        /// List certificates for this project.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.ListCertificatesResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.OpenAI.OpenApiClient.Models.ListCertificatesResponse?> GetAsync(Action<RequestConfiguration<global::Soenneker.OpenAI.OpenApiClient.Organization.Projects.Item.Certificates.CertificatesRequestBuilder.CertificatesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.OpenAI.OpenApiClient.Models.ListCertificatesResponse> GetAsync(Action<RequestConfiguration<global::Soenneker.OpenAI.OpenApiClient.Organization.Projects.Item.Certificates.CertificatesRequestBuilder.CertificatesRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.OpenAI.OpenApiClient.Models.ListCertificatesResponse>(requestInfo, global::Soenneker.OpenAI.OpenApiClient.Models.ListCertificatesResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// List certificates for this project.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.OpenAI.OpenApiClient.Organization.Projects.Item.Certificates.CertificatesRequestBuilder.CertificatesRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.OpenAI.OpenApiClient.Organization.Projects.Item.Certificates.CertificatesRequestBuilder.CertificatesRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenAI.OpenApiClient.Organization.Projects.Item.Certificates.CertificatesRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.OpenAI.OpenApiClient.Organization.Projects.Item.Certificates.CertificatesRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.OpenAI.OpenApiClient.Organization.Projects.Item.Certificates.CertificatesRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// List certificates for this project.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CertificatesRequestBuilderGetQueryParameters 
        {
            /// <summary>A cursor for use in pagination. `after` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, ending with obj_foo, your subsequent call can include after=obj_foo in order to fetch the next page of the list.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("after")]
            public string? After { get; set; }
#nullable restore
#else
            [QueryParameter("after")]
            public string After { get; set; }
#endif
            /// <summary>A limit on the number of objects to be returned. Limit can range between 1 and 100, and the default is 20.</summary>
            [QueryParameter("limit")]
            public int? Limit { get; set; }
            /// <summary>Sort order by the `created_at` timestamp of the objects. `asc` for ascending order and `desc` for descending order.</summary>
            [QueryParameter("order")]
            public global::Soenneker.OpenAI.OpenApiClient.Organization.Projects.Item.Certificates.GetOrderQueryParameterType? Order { get; set; }
        }
    }
}
#pragma warning restore CS0618
