// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.OpenAI.OpenApiClient.Organization.Usage.File_search_calls
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetGroup_byQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "project_id")]
        #pragma warning disable CS1591
        Project_id,
        #pragma warning restore CS1591
        [EnumMember(Value = "user_id")]
        #pragma warning disable CS1591
        User_id,
        #pragma warning restore CS1591
        [EnumMember(Value = "api_key_id")]
        #pragma warning disable CS1591
        Api_key_id,
        #pragma warning restore CS1591
        [EnumMember(Value = "vector_store_id")]
        #pragma warning disable CS1591
        Vector_store_id,
        #pragma warning restore CS1591
    }
}
