// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.OpenAI.OpenApiClient.Agents.Sessions.Item.Artifacts.Item;
using Soenneker.OpenAI.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.OpenAI.OpenApiClient.Agents.Sessions.Item.Artifacts
{
    /// <summary>
    /// Builds and executes requests for operations under \agents\sessions\{sessionId}\artifacts
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ArtifactsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.OpenAI.OpenApiClient.agents.sessions.item.artifacts.item collection</summary>
        /// <param name="position">The immutable session artifact ID.</param>
        /// <returns>A <see cref="global::Soenneker.OpenAI.OpenApiClient.Agents.Sessions.Item.Artifacts.Item.WithArtifactItemRequestBuilder"/></returns>
        public global::Soenneker.OpenAI.OpenApiClient.Agents.Sessions.Item.Artifacts.Item.WithArtifactItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("artifactId", position);
                return new global::Soenneker.OpenAI.OpenApiClient.Agents.Sessions.Item.Artifacts.Item.WithArtifactItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenAI.OpenApiClient.Agents.Sessions.Item.Artifacts.ArtifactsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ArtifactsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/agents/sessions/{sessionId}/artifacts{?after*,environment_id*,limit*,order*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenAI.OpenApiClient.Agents.Sessions.Item.Artifacts.ArtifactsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ArtifactsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/agents/sessions/{sessionId}/artifacts{?after*,environment_id*,limit*,order*}", rawUrl)
        {
        }
        /// <summary>
        /// Lists immutable artifacts published by completed hosted session turns. See [session artifacts](https://developers.openai.com/api/docs/guides/agents-api/environments/files#openai-hosted-artifacts).
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenAI.OpenApiClient.Models.SessionArtifactListResource"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.OpenAI.OpenApiClient.Models.ErrorResponse2">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.OpenAI.OpenApiClient.Models.ErrorResponse2">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.OpenAI.OpenApiClient.Models.ErrorResponse2">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.OpenAI.OpenApiClient.Models.ErrorResponse2">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.OpenAI.OpenApiClient.Models.ErrorResponse2">When receiving a 409 status code</exception>
        /// <exception cref="global::Soenneker.OpenAI.OpenApiClient.Models.ErrorResponse2">When receiving a 500 status code</exception>
        /// <exception cref="global::Soenneker.OpenAI.OpenApiClient.Models.ErrorResponse2">When receiving a 503 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.OpenAI.OpenApiClient.Models.SessionArtifactListResource?> GetAsync(Action<RequestConfiguration<global::Soenneker.OpenAI.OpenApiClient.Agents.Sessions.Item.Artifacts.ArtifactsRequestBuilder.ArtifactsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.OpenAI.OpenApiClient.Models.SessionArtifactListResource> GetAsync(Action<RequestConfiguration<global::Soenneker.OpenAI.OpenApiClient.Agents.Sessions.Item.Artifacts.ArtifactsRequestBuilder.ArtifactsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.OpenAI.OpenApiClient.Models.ErrorResponse2.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.OpenAI.OpenApiClient.Models.ErrorResponse2.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.OpenAI.OpenApiClient.Models.ErrorResponse2.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.OpenAI.OpenApiClient.Models.ErrorResponse2.CreateFromDiscriminatorValue },
                { "409", global::Soenneker.OpenAI.OpenApiClient.Models.ErrorResponse2.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.OpenAI.OpenApiClient.Models.ErrorResponse2.CreateFromDiscriminatorValue },
                { "503", global::Soenneker.OpenAI.OpenApiClient.Models.ErrorResponse2.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.OpenAI.OpenApiClient.Models.SessionArtifactListResource>(requestInfo, global::Soenneker.OpenAI.OpenApiClient.Models.SessionArtifactListResource.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Lists immutable artifacts published by completed hosted session turns. See [session artifacts](https://developers.openai.com/api/docs/guides/agents-api/environments/files#openai-hosted-artifacts).
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.OpenAI.OpenApiClient.Agents.Sessions.Item.Artifacts.ArtifactsRequestBuilder.ArtifactsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.OpenAI.OpenApiClient.Agents.Sessions.Item.Artifacts.ArtifactsRequestBuilder.ArtifactsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenAI.OpenApiClient.Agents.Sessions.Item.Artifacts.ArtifactsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.OpenAI.OpenApiClient.Agents.Sessions.Item.Artifacts.ArtifactsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.OpenAI.OpenApiClient.Agents.Sessions.Item.Artifacts.ArtifactsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Lists immutable artifacts published by completed hosted session turns. See [session artifacts](https://developers.openai.com/api/docs/guides/agents-api/environments/files#openai-hosted-artifacts).
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ArtifactsRequestBuilderGetQueryParameters 
        {
            /// <summary>Return resources after this resource ID in the selected order.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("after")]
            public string? After { get; set; }
#nullable restore
#else
            [QueryParameter("after")]
            public string After { get; set; }
#endif
            /// <summary>Restrict the listing to artifacts produced by this environment.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("environment_id")]
            public string? EnvironmentId { get; set; }
#nullable restore
#else
            [QueryParameter("environment_id")]
            public string EnvironmentId { get; set; }
#endif
            /// <summary>The maximum number of resources to return, between 1 and 100. Defaults to 20.</summary>
            [QueryParameter("limit")]
            public long? Limit { get; set; }
            /// <summary>The order in which resources are returned. Defaults to `desc`.</summary>
            [QueryParameter("order")]
            public global::Soenneker.OpenAI.OpenApiClient.Models.ListOrderParam? Order { get; set; }
        }
    }
}
#pragma warning restore CS0618
